; generated by qd0c from /Users/Shared/ccc/c0computer/compiler/py0/py0c/test_for.qd
source_filename = "/Users/Shared/ccc/c0computer/compiler/py0/py0c/test_for.qd"

; ---- qd0lib 宣告 ----
%QdObj  = type opaque
%QdIter = type opaque

declare %QdObj*  @qd_none()
declare %QdObj*  @qd_bool(i32)
declare %QdObj*  @qd_int(i64)
declare %QdObj*  @qd_float(double)
declare %QdObj*  @qd_string(i8*)
declare %QdObj*  @qd_list_new()
declare %QdObj*  @qd_map_new()
declare %QdObj*  @qd_add(%QdObj*, %QdObj*)
declare %QdObj*  @qd_sub(%QdObj*, %QdObj*)
declare %QdObj*  @qd_mul(%QdObj*, %QdObj*)
declare %QdObj*  @qd_div(%QdObj*, %QdObj*)
declare %QdObj*  @qd_floordiv(%QdObj*, %QdObj*)
declare %QdObj*  @qd_mod(%QdObj*, %QdObj*)
declare %QdObj*  @qd_pow(%QdObj*, %QdObj*)
declare %QdObj*  @qd_neg(%QdObj*)
declare %QdObj*  @qd_not(%QdObj*)
declare %QdObj*  @qd_bitand(%QdObj*, %QdObj*)
declare %QdObj*  @qd_bitor(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_eq(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_ne(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_lt(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_le(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_gt(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_ge(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_is(%QdObj*, %QdObj*)
declare %QdObj*  @qd_getattr(%QdObj*, i8*)
declare void      @qd_setattr(%QdObj*, i8*, %QdObj*)
declare %QdObj*  @qd_getitem(%QdObj*, %QdObj*)
declare void      @qd_setitem(%QdObj*, %QdObj*, %QdObj*)
declare void      @qd_list_append(%QdObj*, %QdObj*)
declare %QdIter* @qd_iter_new(%QdObj*)
declare %QdObj*  @qd_iter_next(%QdIter*)
declare i32       @qd_iter_done(%QdIter*)
declare %QdObj*  @qd_call(%QdObj*, %QdObj**, i32)
declare i32       @qd_truthy(%QdObj*)
declare void      @qd_print(%QdObj*)
declare void      @qd_env_init()
declare void      @qd_env_set(i8*, %QdObj*)
declare %QdObj*  @qd_env_get(i8*)
declare void      @exit(i32) noreturn

@.str.0 = private unnamed_addr constant [3 x i8] c"t0\00"
@.str.1 = private unnamed_addr constant [4 x i8] c"sum\00"
@.str.2 = private unnamed_addr constant [3 x i8] c"t1\00"
@.str.3 = private unnamed_addr constant [3 x i8] c"t2\00"
@.str.4 = private unnamed_addr constant [2 x i8] c"i\00"
@.str.5 = private unnamed_addr constant [12 x i8] c"__range_end\00"
@.str.6 = private unnamed_addr constant [4 x i8] c"L_0\00"
@.str.7 = private unnamed_addr constant [3 x i8] c"t3\00"
@.str.8 = private unnamed_addr constant [3 x i8] c"t5\00"
@.str.9 = private unnamed_addr constant [3 x i8] c"t4\00"
@.str.10 = private unnamed_addr constant [4 x i8] c"L_1\00"
@.str.11 = private unnamed_addr constant [3 x i8] c"t6\00"
@.str.12 = private unnamed_addr constant [3 x i8] c"t7\00"
@.str.13 = private unnamed_addr constant [3 x i8] c"t8\00"
@.str.14 = private unnamed_addr constant [4 x i8] c"t11\00"
@.str.15 = private unnamed_addr constant [4 x i8] c"t10\00"
@.str.16 = private unnamed_addr constant [3 x i8] c"t9\00"
@.str.17 = private unnamed_addr constant [4 x i8] c"t12\00"
@.str.18 = private unnamed_addr constant [6 x i8] c"print\00"
@.str.19 = private unnamed_addr constant [4 x i8] c"t13\00"
@.str.20 = private unnamed_addr constant [4 x i8] c"t14\00"

define %QdObj* @main() {
entry:
  call void @qd_env_init()

  %t0_slot = alloca %QdObj*
  %sum_slot = alloca %QdObj*
  %t1_slot = alloca %QdObj*
  %t2_slot = alloca %QdObj*
  %i_slot = alloca %QdObj*
  %__range_end_slot = alloca %QdObj*
  %t3_slot = alloca %QdObj*
  %t5_slot = alloca %QdObj*
  %t4_slot = alloca %QdObj*
  %L_1_slot = alloca %QdObj*
  %t6_slot = alloca %QdObj*
  %t7_slot = alloca %QdObj*
  %t8_slot = alloca %QdObj*
  %t11_slot = alloca %QdObj*
  %t10_slot = alloca %QdObj*
  %t9_slot = alloca %QdObj*
  %t12_slot = alloca %QdObj*
  %t13_slot = alloca %QdObj*
  %t14_slot = alloca %QdObj*

  %_v0 = call %QdObj* @qd_int(i64 0)
  store %QdObj* %_v0, %QdObj** %t0_slot
  %_v1 = load %QdObj*, %QdObj** %t0_slot
  store %QdObj* %_v1, %QdObj** %sum_slot
  %_cs2 = getelementptr inbounds [4 x i8], [4 x i8]* @.str.1, i32 0, i32 0
  call void @qd_env_set(i8* %_cs2, %QdObj* %_v1)
  %_v3 = call %QdObj* @qd_int(i64 5)
  store %QdObj* %_v3, %QdObj** %t1_slot
  %_v4 = call %QdObj* @qd_int(i64 0)
  store %QdObj* %_v4, %QdObj** %t2_slot
  %_v5 = load %QdObj*, %QdObj** %t2_slot
  store %QdObj* %_v5, %QdObj** %i_slot
  %_cs6 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.4, i32 0, i32 0
  call void @qd_env_set(i8* %_cs6, %QdObj* %_v5)
  %_v7 = load %QdObj*, %QdObj** %t1_slot
  store %QdObj* %_v7, %QdObj** %__range_end_slot
  %_cs8 = getelementptr inbounds [12 x i8], [12 x i8]* @.str.5, i32 0, i32 0
  call void @qd_env_set(i8* %_cs8, %QdObj* %_v7)
  br label %L_0

L_0:
  %_cs9 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.4, i32 0, i32 0
  %_ln10 = call %QdObj* @qd_env_get(i8* %_cs9)
  store %QdObj* %_ln10, %QdObj** %t3_slot
  %_cs11 = getelementptr inbounds [12 x i8], [12 x i8]* @.str.5, i32 0, i32 0
  %_ln12 = call %QdObj* @qd_env_get(i8* %_cs11)
  store %QdObj* %_ln12, %QdObj** %t5_slot
  %_v13 = load %QdObj*, %QdObj** %t3_slot
  %_v14 = load %QdObj*, %QdObj** %t5_slot
  %_cm15 = call %QdObj* @qd_cmp_lt(%QdObj* %_v13, %QdObj* %_v14)
  store %QdObj* %_cm15, %QdObj** %t4_slot
  %_v16 = load %QdObj*, %QdObj** %t4_slot
  %_bt17 = call i32 @qd_truthy(%QdObj* %_v16)
  %_bc18 = icmp ne i32 %_bt17, 0
  br i1 %_bc18, label %_fall19, label %L_1

_fall19:
  %_cs20 = getelementptr inbounds [4 x i8], [4 x i8]* @.str.1, i32 0, i32 0
  %_ln21 = call %QdObj* @qd_env_get(i8* %_cs20)
  store %QdObj* %_ln21, %QdObj** %t6_slot
  %_cs22 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.4, i32 0, i32 0
  %_ln23 = call %QdObj* @qd_env_get(i8* %_cs22)
  store %QdObj* %_ln23, %QdObj** %t7_slot
  %_v24 = load %QdObj*, %QdObj** %t6_slot
  %_v25 = load %QdObj*, %QdObj** %t7_slot
  %_ar26 = call %QdObj* @qd_add(%QdObj* %_v24, %QdObj* %_v25)
  store %QdObj* %_ar26, %QdObj** %t8_slot
  %_v27 = load %QdObj*, %QdObj** %t8_slot
  store %QdObj* %_v27, %QdObj** %sum_slot
  %_cs28 = getelementptr inbounds [4 x i8], [4 x i8]* @.str.1, i32 0, i32 0
  call void @qd_env_set(i8* %_cs28, %QdObj* %_v27)
  %_v29 = call %QdObj* @qd_int(i64 1)
  store %QdObj* %_v29, %QdObj** %t11_slot
  %_cs30 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.4, i32 0, i32 0
  %_ln31 = call %QdObj* @qd_env_get(i8* %_cs30)
  store %QdObj* %_ln31, %QdObj** %t10_slot
  %_v32 = load %QdObj*, %QdObj** %t10_slot
  %_v33 = load %QdObj*, %QdObj** %t11_slot
  %_ar34 = call %QdObj* @qd_add(%QdObj* %_v32, %QdObj* %_v33)
  store %QdObj* %_ar34, %QdObj** %t9_slot
  %_v35 = load %QdObj*, %QdObj** %t9_slot
  store %QdObj* %_v35, %QdObj** %i_slot
  %_cs36 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.4, i32 0, i32 0
  call void @qd_env_set(i8* %_cs36, %QdObj* %_v35)
  br label %L_0

L_1:
  %_cs37 = getelementptr inbounds [4 x i8], [4 x i8]* @.str.1, i32 0, i32 0
  %_ln38 = call %QdObj* @qd_env_get(i8* %_cs37)
  store %QdObj* %_ln38, %QdObj** %t12_slot
  %_v39 = load %QdObj*, %QdObj** %t12_slot
  %_cs40 = getelementptr inbounds [6 x i8], [6 x i8]* @.str.18, i32 0, i32 0
  %_ln41 = call %QdObj* @qd_env_get(i8* %_cs40)
  store %QdObj* %_ln41, %QdObj** %t13_slot
  %_v42 = load %QdObj*, %QdObj** %t13_slot
  %_argv43 = alloca %QdObj*, i32 1
  %_ap44 = getelementptr %QdObj*, %QdObj** %_argv43, i32 0
  store %QdObj* %_v39, %QdObj** %_ap44
  %_cr45 = call %QdObj* @qd_call(%QdObj* %_v42, %QdObj** %_argv43, i32 1)
  store %QdObj* %_cr45, %QdObj** %t14_slot

  ret %QdObj* zeroinitializer
}
