; generated by qd0c from /Users/Shared/ccc/c0computer/compiler/py0/py0c/test_comprehensive.qd
source_filename = "/Users/Shared/ccc/c0computer/compiler/py0/py0c/test_comprehensive.qd"

; ---- qd0lib 宣告 ----
%QdObj  = type opaque
%QdIter = type opaque

declare %QdObj*  @qd_none()
declare %QdObj*  @qd_bool(i32)
declare %QdObj*  @qd_int(i64)
declare %QdObj*  @qd_float(double)
declare %QdObj*  @qd_string(i8*)
declare %QdObj*  @qd_list_new()
declare %QdObj*  @qd_map_new()
declare %QdObj*  @qd_add(%QdObj*, %QdObj*)
declare %QdObj*  @qd_sub(%QdObj*, %QdObj*)
declare %QdObj*  @qd_mul(%QdObj*, %QdObj*)
declare %QdObj*  @qd_div(%QdObj*, %QdObj*)
declare %QdObj*  @qd_floordiv(%QdObj*, %QdObj*)
declare %QdObj*  @qd_mod(%QdObj*, %QdObj*)
declare %QdObj*  @qd_pow(%QdObj*, %QdObj*)
declare %QdObj*  @qd_neg(%QdObj*)
declare %QdObj*  @qd_not(%QdObj*)
declare %QdObj*  @qd_bitand(%QdObj*, %QdObj*)
declare %QdObj*  @qd_bitor(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_eq(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_ne(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_lt(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_le(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_gt(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_ge(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_is(%QdObj*, %QdObj*)
declare %QdObj*  @qd_getattr(%QdObj*, i8*)
declare void      @qd_setattr(%QdObj*, i8*, %QdObj*)
declare %QdObj*  @qd_getitem(%QdObj*, %QdObj*)
declare void      @qd_setitem(%QdObj*, %QdObj*, %QdObj*)
declare void      @qd_list_append(%QdObj*, %QdObj*)
declare %QdIter* @qd_iter_new(%QdObj*)
declare %QdObj*  @qd_iter_next(%QdIter*)
declare i32       @qd_iter_done(%QdIter*)
declare %QdObj*  @qd_call(%QdObj*, %QdObj**, i32)
declare i32       @qd_truthy(%QdObj*)
declare void      @qd_print(%QdObj*)
declare void      @qd_env_init()
declare void      @qd_env_set(i8*, %QdObj*)
declare %QdObj*  @qd_env_get(i8*)
declare void      @exit(i32) noreturn

@.str.0 = private unnamed_addr constant [3 x i8] c"t0\00"
@.str.1 = private unnamed_addr constant [4 x i8] c"sum\00"
@.str.2 = private unnamed_addr constant [3 x i8] c"t1\00"
@.str.3 = private unnamed_addr constant [3 x i8] c"t2\00"
@.str.4 = private unnamed_addr constant [2 x i8] c"i\00"
@.str.5 = private unnamed_addr constant [12 x i8] c"__range_end\00"
@.str.6 = private unnamed_addr constant [4 x i8] c"L_0\00"
@.str.7 = private unnamed_addr constant [3 x i8] c"t3\00"
@.str.8 = private unnamed_addr constant [3 x i8] c"t5\00"
@.str.9 = private unnamed_addr constant [3 x i8] c"t4\00"
@.str.10 = private unnamed_addr constant [4 x i8] c"L_1\00"
@.str.11 = private unnamed_addr constant [3 x i8] c"t6\00"
@.str.12 = private unnamed_addr constant [3 x i8] c"t7\00"
@.str.13 = private unnamed_addr constant [3 x i8] c"t8\00"
@.str.14 = private unnamed_addr constant [4 x i8] c"L_2\00"
@.str.15 = private unnamed_addr constant [3 x i8] c"t9\00"
@.str.16 = private unnamed_addr constant [4 x i8] c"t10\00"
@.str.17 = private unnamed_addr constant [4 x i8] c"t11\00"
@.str.18 = private unnamed_addr constant [4 x i8] c"L_3\00"
@.str.19 = private unnamed_addr constant [4 x i8] c"t12\00"
@.str.20 = private unnamed_addr constant [4 x i8] c"t13\00"
@.str.21 = private unnamed_addr constant [4 x i8] c"t14\00"
@.str.22 = private unnamed_addr constant [4 x i8] c"t17\00"
@.str.23 = private unnamed_addr constant [4 x i8] c"t16\00"
@.str.24 = private unnamed_addr constant [4 x i8] c"t15\00"
@.str.25 = private unnamed_addr constant [4 x i8] c"t18\00"
@.str.26 = private unnamed_addr constant [6 x i8] c"print\00"
@.str.27 = private unnamed_addr constant [4 x i8] c"t19\00"
@.str.28 = private unnamed_addr constant [4 x i8] c"t20\00"

define %QdObj* @main() {
entry:
  call void @qd_env_init()

  %t0_slot = alloca %QdObj*
  %sum_slot = alloca %QdObj*
  %t1_slot = alloca %QdObj*
  %t2_slot = alloca %QdObj*
  %i_slot = alloca %QdObj*
  %__range_end_slot = alloca %QdObj*
  %t3_slot = alloca %QdObj*
  %t5_slot = alloca %QdObj*
  %t4_slot = alloca %QdObj*
  %L_1_slot = alloca %QdObj*
  %t6_slot = alloca %QdObj*
  %t7_slot = alloca %QdObj*
  %t8_slot = alloca %QdObj*
  %L_2_slot = alloca %QdObj*
  %t9_slot = alloca %QdObj*
  %t10_slot = alloca %QdObj*
  %t11_slot = alloca %QdObj*
  %t12_slot = alloca %QdObj*
  %t13_slot = alloca %QdObj*
  %t14_slot = alloca %QdObj*
  %t17_slot = alloca %QdObj*
  %t16_slot = alloca %QdObj*
  %t15_slot = alloca %QdObj*
  %t18_slot = alloca %QdObj*
  %t19_slot = alloca %QdObj*
  %t20_slot = alloca %QdObj*

  %_v0 = call %QdObj* @qd_int(i64 0)
  store %QdObj* %_v0, %QdObj** %t0_slot
  %_v1 = load %QdObj*, %QdObj** %t0_slot
  store %QdObj* %_v1, %QdObj** %sum_slot
  %_cs2 = getelementptr inbounds [4 x i8], [4 x i8]* @.str.1, i32 0, i32 0
  call void @qd_env_set(i8* %_cs2, %QdObj* %_v1)
  %_v3 = call %QdObj* @qd_int(i64 10)
  store %QdObj* %_v3, %QdObj** %t1_slot
  %_v4 = call %QdObj* @qd_int(i64 0)
  store %QdObj* %_v4, %QdObj** %t2_slot
  %_v5 = load %QdObj*, %QdObj** %t2_slot
  store %QdObj* %_v5, %QdObj** %i_slot
  %_cs6 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.4, i32 0, i32 0
  call void @qd_env_set(i8* %_cs6, %QdObj* %_v5)
  %_v7 = load %QdObj*, %QdObj** %t1_slot
  store %QdObj* %_v7, %QdObj** %__range_end_slot
  %_cs8 = getelementptr inbounds [12 x i8], [12 x i8]* @.str.5, i32 0, i32 0
  call void @qd_env_set(i8* %_cs8, %QdObj* %_v7)
  br label %L_0

L_0:
  %_cs9 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.4, i32 0, i32 0
  %_ln10 = call %QdObj* @qd_env_get(i8* %_cs9)
  store %QdObj* %_ln10, %QdObj** %t3_slot
  %_cs11 = getelementptr inbounds [12 x i8], [12 x i8]* @.str.5, i32 0, i32 0
  %_ln12 = call %QdObj* @qd_env_get(i8* %_cs11)
  store %QdObj* %_ln12, %QdObj** %t5_slot
  %_v13 = load %QdObj*, %QdObj** %t3_slot
  %_v14 = load %QdObj*, %QdObj** %t5_slot
  %_cm15 = call %QdObj* @qd_cmp_lt(%QdObj* %_v13, %QdObj* %_v14)
  store %QdObj* %_cm15, %QdObj** %t4_slot
  %_v16 = load %QdObj*, %QdObj** %t4_slot
  %_bt17 = call i32 @qd_truthy(%QdObj* %_v16)
  %_bc18 = icmp ne i32 %_bt17, 0
  br i1 %_bc18, label %_fall19, label %L_1

_fall19:
  %_cs20 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.4, i32 0, i32 0
  %_ln21 = call %QdObj* @qd_env_get(i8* %_cs20)
  store %QdObj* %_ln21, %QdObj** %t6_slot
  %_v22 = call %QdObj* @qd_int(i64 5)
  store %QdObj* %_v22, %QdObj** %t7_slot
  %_v23 = load %QdObj*, %QdObj** %t6_slot
  %_v24 = load %QdObj*, %QdObj** %t7_slot
  %_cm25 = call %QdObj* @qd_cmp_gt(%QdObj* %_v23, %QdObj* %_v24)
  store %QdObj* %_cm25, %QdObj** %t8_slot
  %_v26 = load %QdObj*, %QdObj** %t8_slot
  %_bt27 = call i32 @qd_truthy(%QdObj* %_v26)
  %_bc28 = icmp ne i32 %_bt27, 0
  br i1 %_bc28, label %_fall29, label %L_2

_fall29:
  %_cs30 = getelementptr inbounds [4 x i8], [4 x i8]* @.str.1, i32 0, i32 0
  %_ln31 = call %QdObj* @qd_env_get(i8* %_cs30)
  store %QdObj* %_ln31, %QdObj** %t9_slot
  %_cs32 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.4, i32 0, i32 0
  %_ln33 = call %QdObj* @qd_env_get(i8* %_cs32)
  store %QdObj* %_ln33, %QdObj** %t10_slot
  %_v34 = load %QdObj*, %QdObj** %t9_slot
  %_v35 = load %QdObj*, %QdObj** %t10_slot
  %_ar36 = call %QdObj* @qd_add(%QdObj* %_v34, %QdObj* %_v35)
  store %QdObj* %_ar36, %QdObj** %t11_slot
  %_v37 = load %QdObj*, %QdObj** %t11_slot
  store %QdObj* %_v37, %QdObj** %sum_slot
  %_cs38 = getelementptr inbounds [4 x i8], [4 x i8]* @.str.1, i32 0, i32 0
  call void @qd_env_set(i8* %_cs38, %QdObj* %_v37)
  br label %L_3

L_2:
  %_cs39 = getelementptr inbounds [4 x i8], [4 x i8]* @.str.1, i32 0, i32 0
  %_ln40 = call %QdObj* @qd_env_get(i8* %_cs39)
  store %QdObj* %_ln40, %QdObj** %t12_slot
  %_v41 = call %QdObj* @qd_int(i64 1)
  store %QdObj* %_v41, %QdObj** %t13_slot
  %_v42 = load %QdObj*, %QdObj** %t12_slot
  %_v43 = load %QdObj*, %QdObj** %t13_slot
  %_ar44 = call %QdObj* @qd_add(%QdObj* %_v42, %QdObj* %_v43)
  store %QdObj* %_ar44, %QdObj** %t14_slot
  %_v45 = load %QdObj*, %QdObj** %t14_slot
  store %QdObj* %_v45, %QdObj** %sum_slot
  %_cs46 = getelementptr inbounds [4 x i8], [4 x i8]* @.str.1, i32 0, i32 0
  call void @qd_env_set(i8* %_cs46, %QdObj* %_v45)
  br label %L_3

L_3:
  %_v47 = call %QdObj* @qd_int(i64 1)
  store %QdObj* %_v47, %QdObj** %t17_slot
  %_cs48 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.4, i32 0, i32 0
  %_ln49 = call %QdObj* @qd_env_get(i8* %_cs48)
  store %QdObj* %_ln49, %QdObj** %t16_slot
  %_v50 = load %QdObj*, %QdObj** %t16_slot
  %_v51 = load %QdObj*, %QdObj** %t17_slot
  %_ar52 = call %QdObj* @qd_add(%QdObj* %_v50, %QdObj* %_v51)
  store %QdObj* %_ar52, %QdObj** %t15_slot
  %_v53 = load %QdObj*, %QdObj** %t15_slot
  store %QdObj* %_v53, %QdObj** %i_slot
  %_cs54 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.4, i32 0, i32 0
  call void @qd_env_set(i8* %_cs54, %QdObj* %_v53)
  br label %L_0

L_1:
  %_cs55 = getelementptr inbounds [4 x i8], [4 x i8]* @.str.1, i32 0, i32 0
  %_ln56 = call %QdObj* @qd_env_get(i8* %_cs55)
  store %QdObj* %_ln56, %QdObj** %t18_slot
  %_v57 = load %QdObj*, %QdObj** %t18_slot
  %_cs58 = getelementptr inbounds [6 x i8], [6 x i8]* @.str.26, i32 0, i32 0
  %_ln59 = call %QdObj* @qd_env_get(i8* %_cs58)
  store %QdObj* %_ln59, %QdObj** %t19_slot
  %_v60 = load %QdObj*, %QdObj** %t19_slot
  %_argv61 = alloca %QdObj*, i32 1
  %_ap62 = getelementptr %QdObj*, %QdObj** %_argv61, i32 0
  store %QdObj* %_v57, %QdObj** %_ap62
  %_cr63 = call %QdObj* @qd_call(%QdObj* %_v60, %QdObj** %_argv61, i32 1)
  store %QdObj* %_cr63, %QdObj** %t20_slot

  ret %QdObj* zeroinitializer
}
