; generated by qd0c from /Users/Shared/ccc/c0computer/compiler/py0/py0c/test_compare.qd
source_filename = "/Users/Shared/ccc/c0computer/compiler/py0/py0c/test_compare.qd"

; ---- qd0lib 宣告 ----
%QdObj  = type opaque
%QdIter = type opaque

declare %QdObj*  @qd_none()
declare %QdObj*  @qd_bool(i32)
declare %QdObj*  @qd_int(i64)
declare %QdObj*  @qd_float(double)
declare %QdObj*  @qd_string(i8*)
declare %QdObj*  @qd_list_new()
declare %QdObj*  @qd_map_new()
declare %QdObj*  @qd_add(%QdObj*, %QdObj*)
declare %QdObj*  @qd_sub(%QdObj*, %QdObj*)
declare %QdObj*  @qd_mul(%QdObj*, %QdObj*)
declare %QdObj*  @qd_div(%QdObj*, %QdObj*)
declare %QdObj*  @qd_floordiv(%QdObj*, %QdObj*)
declare %QdObj*  @qd_mod(%QdObj*, %QdObj*)
declare %QdObj*  @qd_pow(%QdObj*, %QdObj*)
declare %QdObj*  @qd_neg(%QdObj*)
declare %QdObj*  @qd_not(%QdObj*)
declare %QdObj*  @qd_bitand(%QdObj*, %QdObj*)
declare %QdObj*  @qd_bitor(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_eq(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_ne(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_lt(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_le(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_gt(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_ge(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_is(%QdObj*, %QdObj*)
declare %QdObj*  @qd_getattr(%QdObj*, i8*)
declare void      @qd_setattr(%QdObj*, i8*, %QdObj*)
declare %QdObj*  @qd_getitem(%QdObj*, %QdObj*)
declare void      @qd_setitem(%QdObj*, %QdObj*, %QdObj*)
declare void      @qd_list_append(%QdObj*, %QdObj*)
declare %QdIter* @qd_iter_new(%QdObj*)
declare %QdObj*  @qd_iter_next(%QdIter*)
declare i32       @qd_iter_done(%QdIter*)
declare %QdObj*  @qd_call(%QdObj*, %QdObj**, i32)
declare i32       @qd_truthy(%QdObj*)
declare void      @qd_print(%QdObj*)
declare void      @qd_env_init()
declare void      @qd_env_set(i8*, %QdObj*)
declare %QdObj*  @qd_env_get(i8*)
declare void      @exit(i32) noreturn

@.str.0 = private unnamed_addr constant [3 x i8] c"t0\00"
@.str.1 = private unnamed_addr constant [2 x i8] c"x\00"
@.str.2 = private unnamed_addr constant [3 x i8] c"t1\00"
@.str.3 = private unnamed_addr constant [2 x i8] c"y\00"
@.str.4 = private unnamed_addr constant [3 x i8] c"t2\00"
@.str.5 = private unnamed_addr constant [3 x i8] c"t3\00"
@.str.6 = private unnamed_addr constant [3 x i8] c"t4\00"
@.str.7 = private unnamed_addr constant [4 x i8] c"L_0\00"
@.str.8 = private unnamed_addr constant [6 x i8] c"x > y\00"
@.str.9 = private unnamed_addr constant [3 x i8] c"t5\00"
@.str.10 = private unnamed_addr constant [6 x i8] c"print\00"
@.str.11 = private unnamed_addr constant [3 x i8] c"t6\00"
@.str.12 = private unnamed_addr constant [3 x i8] c"t7\00"
@.str.13 = private unnamed_addr constant [4 x i8] c"L_1\00"
@.str.14 = private unnamed_addr constant [3 x i8] c"t8\00"
@.str.15 = private unnamed_addr constant [3 x i8] c"t9\00"
@.str.16 = private unnamed_addr constant [4 x i8] c"t10\00"
@.str.17 = private unnamed_addr constant [4 x i8] c"L_2\00"
@.str.18 = private unnamed_addr constant [5 x i8] c"FAIL\00"
@.str.19 = private unnamed_addr constant [4 x i8] c"t11\00"
@.str.20 = private unnamed_addr constant [4 x i8] c"t12\00"
@.str.21 = private unnamed_addr constant [4 x i8] c"t13\00"
@.str.22 = private unnamed_addr constant [4 x i8] c"L_3\00"
@.str.23 = private unnamed_addr constant [5 x i8] c"PASS\00"
@.str.24 = private unnamed_addr constant [4 x i8] c"t14\00"
@.str.25 = private unnamed_addr constant [4 x i8] c"t15\00"
@.str.26 = private unnamed_addr constant [4 x i8] c"t16\00"
@.str.27 = private unnamed_addr constant [4 x i8] c"t17\00"
@.str.28 = private unnamed_addr constant [4 x i8] c"t18\00"
@.str.29 = private unnamed_addr constant [4 x i8] c"t19\00"
@.str.30 = private unnamed_addr constant [4 x i8] c"L_4\00"
@.str.31 = private unnamed_addr constant [8 x i8] c"x >= 10\00"
@.str.32 = private unnamed_addr constant [4 x i8] c"t20\00"
@.str.33 = private unnamed_addr constant [4 x i8] c"t21\00"
@.str.34 = private unnamed_addr constant [4 x i8] c"t22\00"
@.str.35 = private unnamed_addr constant [4 x i8] c"L_5\00"
@.str.36 = private unnamed_addr constant [4 x i8] c"t23\00"
@.str.37 = private unnamed_addr constant [4 x i8] c"t24\00"
@.str.38 = private unnamed_addr constant [4 x i8] c"t25\00"
@.str.39 = private unnamed_addr constant [4 x i8] c"L_6\00"
@.str.40 = private unnamed_addr constant [7 x i8] c"y <= 5\00"
@.str.41 = private unnamed_addr constant [4 x i8] c"t26\00"
@.str.42 = private unnamed_addr constant [4 x i8] c"t27\00"
@.str.43 = private unnamed_addr constant [4 x i8] c"t28\00"
@.str.44 = private unnamed_addr constant [4 x i8] c"L_7\00"
@.str.45 = private unnamed_addr constant [4 x i8] c"t29\00"
@.str.46 = private unnamed_addr constant [4 x i8] c"t30\00"
@.str.47 = private unnamed_addr constant [4 x i8] c"t31\00"
@.str.48 = private unnamed_addr constant [4 x i8] c"L_8\00"
@.str.49 = private unnamed_addr constant [7 x i8] c"x != y\00"
@.str.50 = private unnamed_addr constant [4 x i8] c"t32\00"
@.str.51 = private unnamed_addr constant [4 x i8] c"t33\00"
@.str.52 = private unnamed_addr constant [4 x i8] c"t34\00"
@.str.53 = private unnamed_addr constant [4 x i8] c"L_9\00"
@.str.54 = private unnamed_addr constant [4 x i8] c"t35\00"
@.str.55 = private unnamed_addr constant [4 x i8] c"t36\00"
@.str.56 = private unnamed_addr constant [4 x i8] c"t37\00"
@.str.57 = private unnamed_addr constant [5 x i8] c"L_10\00"
@.str.58 = private unnamed_addr constant [8 x i8] c"x == 10\00"
@.str.59 = private unnamed_addr constant [4 x i8] c"t38\00"
@.str.60 = private unnamed_addr constant [4 x i8] c"t39\00"
@.str.61 = private unnamed_addr constant [4 x i8] c"t40\00"
@.str.62 = private unnamed_addr constant [5 x i8] c"L_11\00"

define %QdObj* @main() {
entry:
  call void @qd_env_init()

  %t0_slot = alloca %QdObj*
  %x_slot = alloca %QdObj*
  %t1_slot = alloca %QdObj*
  %y_slot = alloca %QdObj*
  %t2_slot = alloca %QdObj*
  %t3_slot = alloca %QdObj*
  %t4_slot = alloca %QdObj*
  %L_0_slot = alloca %QdObj*
  %t5_slot = alloca %QdObj*
  %t6_slot = alloca %QdObj*
  %t7_slot = alloca %QdObj*
  %t8_slot = alloca %QdObj*
  %t9_slot = alloca %QdObj*
  %t10_slot = alloca %QdObj*
  %L_2_slot = alloca %QdObj*
  %t11_slot = alloca %QdObj*
  %t12_slot = alloca %QdObj*
  %t13_slot = alloca %QdObj*
  %t14_slot = alloca %QdObj*
  %t15_slot = alloca %QdObj*
  %t16_slot = alloca %QdObj*
  %t17_slot = alloca %QdObj*
  %t18_slot = alloca %QdObj*
  %t19_slot = alloca %QdObj*
  %L_4_slot = alloca %QdObj*
  %t20_slot = alloca %QdObj*
  %t21_slot = alloca %QdObj*
  %t22_slot = alloca %QdObj*
  %t23_slot = alloca %QdObj*
  %t24_slot = alloca %QdObj*
  %t25_slot = alloca %QdObj*
  %L_6_slot = alloca %QdObj*
  %t26_slot = alloca %QdObj*
  %t27_slot = alloca %QdObj*
  %t28_slot = alloca %QdObj*
  %t29_slot = alloca %QdObj*
  %t30_slot = alloca %QdObj*
  %t31_slot = alloca %QdObj*
  %L_8_slot = alloca %QdObj*
  %t32_slot = alloca %QdObj*
  %t33_slot = alloca %QdObj*
  %t34_slot = alloca %QdObj*
  %t35_slot = alloca %QdObj*
  %t36_slot = alloca %QdObj*
  %t37_slot = alloca %QdObj*
  %L_10_slot = alloca %QdObj*
  %t38_slot = alloca %QdObj*
  %t39_slot = alloca %QdObj*
  %t40_slot = alloca %QdObj*

  %_v0 = call %QdObj* @qd_int(i64 10)
  store %QdObj* %_v0, %QdObj** %t0_slot
  %_v1 = load %QdObj*, %QdObj** %t0_slot
  store %QdObj* %_v1, %QdObj** %x_slot
  %_cs2 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.1, i32 0, i32 0
  call void @qd_env_set(i8* %_cs2, %QdObj* %_v1)
  %_v3 = call %QdObj* @qd_int(i64 5)
  store %QdObj* %_v3, %QdObj** %t1_slot
  %_v4 = load %QdObj*, %QdObj** %t1_slot
  store %QdObj* %_v4, %QdObj** %y_slot
  %_cs5 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.3, i32 0, i32 0
  call void @qd_env_set(i8* %_cs5, %QdObj* %_v4)
  %_cs6 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.1, i32 0, i32 0
  %_ln7 = call %QdObj* @qd_env_get(i8* %_cs6)
  store %QdObj* %_ln7, %QdObj** %t2_slot
  %_cs8 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.3, i32 0, i32 0
  %_ln9 = call %QdObj* @qd_env_get(i8* %_cs8)
  store %QdObj* %_ln9, %QdObj** %t3_slot
  %_v10 = load %QdObj*, %QdObj** %t2_slot
  %_v11 = load %QdObj*, %QdObj** %t3_slot
  %_cm12 = call %QdObj* @qd_cmp_gt(%QdObj* %_v10, %QdObj* %_v11)
  store %QdObj* %_cm12, %QdObj** %t4_slot
  %_v13 = load %QdObj*, %QdObj** %t4_slot
  %_bt14 = call i32 @qd_truthy(%QdObj* %_v13)
  %_bc15 = icmp ne i32 %_bt14, 0
  br i1 %_bc15, label %_fall16, label %L_0

_fall16:
  %_gp18 = getelementptr inbounds [6 x i8], [6 x i8]* @.str.8, i32 0, i32 0
  %_v17 = call %QdObj* @qd_string(i8* %_gp18)
  store %QdObj* %_v17, %QdObj** %t5_slot
  %_v19 = load %QdObj*, %QdObj** %t5_slot
  %_cs20 = getelementptr inbounds [6 x i8], [6 x i8]* @.str.10, i32 0, i32 0
  %_ln21 = call %QdObj* @qd_env_get(i8* %_cs20)
  store %QdObj* %_ln21, %QdObj** %t6_slot
  %_v22 = load %QdObj*, %QdObj** %t6_slot
  %_argv23 = alloca %QdObj*, i32 1
  %_ap24 = getelementptr %QdObj*, %QdObj** %_argv23, i32 0
  store %QdObj* %_v19, %QdObj** %_ap24
  %_cr25 = call %QdObj* @qd_call(%QdObj* %_v22, %QdObj** %_argv23, i32 1)
  store %QdObj* %_cr25, %QdObj** %t7_slot
  br label %L_1

L_0:
  br label %L_1

L_1:
  %_cs26 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.1, i32 0, i32 0
  %_ln27 = call %QdObj* @qd_env_get(i8* %_cs26)
  store %QdObj* %_ln27, %QdObj** %t8_slot
  %_cs28 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.3, i32 0, i32 0
  %_ln29 = call %QdObj* @qd_env_get(i8* %_cs28)
  store %QdObj* %_ln29, %QdObj** %t9_slot
  %_v30 = load %QdObj*, %QdObj** %t8_slot
  %_v31 = load %QdObj*, %QdObj** %t9_slot
  %_cm32 = call %QdObj* @qd_cmp_lt(%QdObj* %_v30, %QdObj* %_v31)
  store %QdObj* %_cm32, %QdObj** %t10_slot
  %_v33 = load %QdObj*, %QdObj** %t10_slot
  %_bt34 = call i32 @qd_truthy(%QdObj* %_v33)
  %_bc35 = icmp ne i32 %_bt34, 0
  br i1 %_bc35, label %_fall36, label %L_2

_fall36:
  %_gp38 = getelementptr inbounds [5 x i8], [5 x i8]* @.str.18, i32 0, i32 0
  %_v37 = call %QdObj* @qd_string(i8* %_gp38)
  store %QdObj* %_v37, %QdObj** %t11_slot
  %_v39 = load %QdObj*, %QdObj** %t11_slot
  %_cs40 = getelementptr inbounds [6 x i8], [6 x i8]* @.str.10, i32 0, i32 0
  %_ln41 = call %QdObj* @qd_env_get(i8* %_cs40)
  store %QdObj* %_ln41, %QdObj** %t12_slot
  %_v42 = load %QdObj*, %QdObj** %t12_slot
  %_argv43 = alloca %QdObj*, i32 1
  %_ap44 = getelementptr %QdObj*, %QdObj** %_argv43, i32 0
  store %QdObj* %_v39, %QdObj** %_ap44
  %_cr45 = call %QdObj* @qd_call(%QdObj* %_v42, %QdObj** %_argv43, i32 1)
  store %QdObj* %_cr45, %QdObj** %t13_slot
  br label %L_3

L_2:
  %_gp47 = getelementptr inbounds [5 x i8], [5 x i8]* @.str.23, i32 0, i32 0
  %_v46 = call %QdObj* @qd_string(i8* %_gp47)
  store %QdObj* %_v46, %QdObj** %t14_slot
  %_v48 = load %QdObj*, %QdObj** %t14_slot
  %_cs49 = getelementptr inbounds [6 x i8], [6 x i8]* @.str.10, i32 0, i32 0
  %_ln50 = call %QdObj* @qd_env_get(i8* %_cs49)
  store %QdObj* %_ln50, %QdObj** %t15_slot
  %_v51 = load %QdObj*, %QdObj** %t15_slot
  %_argv52 = alloca %QdObj*, i32 1
  %_ap53 = getelementptr %QdObj*, %QdObj** %_argv52, i32 0
  store %QdObj* %_v48, %QdObj** %_ap53
  %_cr54 = call %QdObj* @qd_call(%QdObj* %_v51, %QdObj** %_argv52, i32 1)
  store %QdObj* %_cr54, %QdObj** %t16_slot
  br label %L_3

L_3:
  %_cs55 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.1, i32 0, i32 0
  %_ln56 = call %QdObj* @qd_env_get(i8* %_cs55)
  store %QdObj* %_ln56, %QdObj** %t17_slot
  %_v57 = call %QdObj* @qd_int(i64 10)
  store %QdObj* %_v57, %QdObj** %t18_slot
  %_v58 = load %QdObj*, %QdObj** %t17_slot
  %_v59 = load %QdObj*, %QdObj** %t18_slot
  %_cm60 = call %QdObj* @qd_cmp_ge(%QdObj* %_v58, %QdObj* %_v59)
  store %QdObj* %_cm60, %QdObj** %t19_slot
  %_v61 = load %QdObj*, %QdObj** %t19_slot
  %_bt62 = call i32 @qd_truthy(%QdObj* %_v61)
  %_bc63 = icmp ne i32 %_bt62, 0
  br i1 %_bc63, label %_fall64, label %L_4

_fall64:
  %_gp66 = getelementptr inbounds [8 x i8], [8 x i8]* @.str.31, i32 0, i32 0
  %_v65 = call %QdObj* @qd_string(i8* %_gp66)
  store %QdObj* %_v65, %QdObj** %t20_slot
  %_v67 = load %QdObj*, %QdObj** %t20_slot
  %_cs68 = getelementptr inbounds [6 x i8], [6 x i8]* @.str.10, i32 0, i32 0
  %_ln69 = call %QdObj* @qd_env_get(i8* %_cs68)
  store %QdObj* %_ln69, %QdObj** %t21_slot
  %_v70 = load %QdObj*, %QdObj** %t21_slot
  %_argv71 = alloca %QdObj*, i32 1
  %_ap72 = getelementptr %QdObj*, %QdObj** %_argv71, i32 0
  store %QdObj* %_v67, %QdObj** %_ap72
  %_cr73 = call %QdObj* @qd_call(%QdObj* %_v70, %QdObj** %_argv71, i32 1)
  store %QdObj* %_cr73, %QdObj** %t22_slot
  br label %L_5

L_4:
  br label %L_5

L_5:
  %_cs74 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.3, i32 0, i32 0
  %_ln75 = call %QdObj* @qd_env_get(i8* %_cs74)
  store %QdObj* %_ln75, %QdObj** %t23_slot
  %_v76 = call %QdObj* @qd_int(i64 5)
  store %QdObj* %_v76, %QdObj** %t24_slot
  %_v77 = load %QdObj*, %QdObj** %t23_slot
  %_v78 = load %QdObj*, %QdObj** %t24_slot
  %_cm79 = call %QdObj* @qd_cmp_le(%QdObj* %_v77, %QdObj* %_v78)
  store %QdObj* %_cm79, %QdObj** %t25_slot
  %_v80 = load %QdObj*, %QdObj** %t25_slot
  %_bt81 = call i32 @qd_truthy(%QdObj* %_v80)
  %_bc82 = icmp ne i32 %_bt81, 0
  br i1 %_bc82, label %_fall83, label %L_6

_fall83:
  %_gp85 = getelementptr inbounds [7 x i8], [7 x i8]* @.str.40, i32 0, i32 0
  %_v84 = call %QdObj* @qd_string(i8* %_gp85)
  store %QdObj* %_v84, %QdObj** %t26_slot
  %_v86 = load %QdObj*, %QdObj** %t26_slot
  %_cs87 = getelementptr inbounds [6 x i8], [6 x i8]* @.str.10, i32 0, i32 0
  %_ln88 = call %QdObj* @qd_env_get(i8* %_cs87)
  store %QdObj* %_ln88, %QdObj** %t27_slot
  %_v89 = load %QdObj*, %QdObj** %t27_slot
  %_argv90 = alloca %QdObj*, i32 1
  %_ap91 = getelementptr %QdObj*, %QdObj** %_argv90, i32 0
  store %QdObj* %_v86, %QdObj** %_ap91
  %_cr92 = call %QdObj* @qd_call(%QdObj* %_v89, %QdObj** %_argv90, i32 1)
  store %QdObj* %_cr92, %QdObj** %t28_slot
  br label %L_7

L_6:
  br label %L_7

L_7:
  %_cs93 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.1, i32 0, i32 0
  %_ln94 = call %QdObj* @qd_env_get(i8* %_cs93)
  store %QdObj* %_ln94, %QdObj** %t29_slot
  %_cs95 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.3, i32 0, i32 0
  %_ln96 = call %QdObj* @qd_env_get(i8* %_cs95)
  store %QdObj* %_ln96, %QdObj** %t30_slot
  %_v97 = load %QdObj*, %QdObj** %t29_slot
  %_v98 = load %QdObj*, %QdObj** %t30_slot
  %_cm99 = call %QdObj* @qd_cmp_ne(%QdObj* %_v97, %QdObj* %_v98)
  store %QdObj* %_cm99, %QdObj** %t31_slot
  %_v100 = load %QdObj*, %QdObj** %t31_slot
  %_bt101 = call i32 @qd_truthy(%QdObj* %_v100)
  %_bc102 = icmp ne i32 %_bt101, 0
  br i1 %_bc102, label %_fall103, label %L_8

_fall103:
  %_gp105 = getelementptr inbounds [7 x i8], [7 x i8]* @.str.49, i32 0, i32 0
  %_v104 = call %QdObj* @qd_string(i8* %_gp105)
  store %QdObj* %_v104, %QdObj** %t32_slot
  %_v106 = load %QdObj*, %QdObj** %t32_slot
  %_cs107 = getelementptr inbounds [6 x i8], [6 x i8]* @.str.10, i32 0, i32 0
  %_ln108 = call %QdObj* @qd_env_get(i8* %_cs107)
  store %QdObj* %_ln108, %QdObj** %t33_slot
  %_v109 = load %QdObj*, %QdObj** %t33_slot
  %_argv110 = alloca %QdObj*, i32 1
  %_ap111 = getelementptr %QdObj*, %QdObj** %_argv110, i32 0
  store %QdObj* %_v106, %QdObj** %_ap111
  %_cr112 = call %QdObj* @qd_call(%QdObj* %_v109, %QdObj** %_argv110, i32 1)
  store %QdObj* %_cr112, %QdObj** %t34_slot
  br label %L_9

L_8:
  br label %L_9

L_9:
  %_cs113 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.1, i32 0, i32 0
  %_ln114 = call %QdObj* @qd_env_get(i8* %_cs113)
  store %QdObj* %_ln114, %QdObj** %t35_slot
  %_v115 = call %QdObj* @qd_int(i64 10)
  store %QdObj* %_v115, %QdObj** %t36_slot
  %_v116 = load %QdObj*, %QdObj** %t35_slot
  %_v117 = load %QdObj*, %QdObj** %t36_slot
  %_cm118 = call %QdObj* @qd_cmp_eq(%QdObj* %_v116, %QdObj* %_v117)
  store %QdObj* %_cm118, %QdObj** %t37_slot
  %_v119 = load %QdObj*, %QdObj** %t37_slot
  %_bt120 = call i32 @qd_truthy(%QdObj* %_v119)
  %_bc121 = icmp ne i32 %_bt120, 0
  br i1 %_bc121, label %_fall122, label %L_10

_fall122:
  %_gp124 = getelementptr inbounds [8 x i8], [8 x i8]* @.str.58, i32 0, i32 0
  %_v123 = call %QdObj* @qd_string(i8* %_gp124)
  store %QdObj* %_v123, %QdObj** %t38_slot
  %_v125 = load %QdObj*, %QdObj** %t38_slot
  %_cs126 = getelementptr inbounds [6 x i8], [6 x i8]* @.str.10, i32 0, i32 0
  %_ln127 = call %QdObj* @qd_env_get(i8* %_cs126)
  store %QdObj* %_ln127, %QdObj** %t39_slot
  %_v128 = load %QdObj*, %QdObj** %t39_slot
  %_argv129 = alloca %QdObj*, i32 1
  %_ap130 = getelementptr %QdObj*, %QdObj** %_argv129, i32 0
  store %QdObj* %_v125, %QdObj** %_ap130
  %_cr131 = call %QdObj* @qd_call(%QdObj* %_v128, %QdObj** %_argv129, i32 1)
  store %QdObj* %_cr131, %QdObj** %t40_slot
  br label %L_11

L_10:
  br label %L_11

L_11:

  ret %QdObj* zeroinitializer
}
