; generated by qd0c from /Users/Shared/ccc/c0computer/compiler/py0/py0c/test_while3.qd
source_filename = "/Users/Shared/ccc/c0computer/compiler/py0/py0c/test_while3.qd"

; ---- qd0lib 宣告 ----
%QdObj  = type opaque
%QdIter = type opaque

declare %QdObj*  @qd_none()
declare %QdObj*  @qd_bool(i32)
declare %QdObj*  @qd_int(i64)
declare %QdObj*  @qd_float(double)
declare %QdObj*  @qd_string(i8*)
declare %QdObj*  @qd_list_new()
declare %QdObj*  @qd_map_new()
declare %QdObj*  @qd_add(%QdObj*, %QdObj*)
declare %QdObj*  @qd_sub(%QdObj*, %QdObj*)
declare %QdObj*  @qd_mul(%QdObj*, %QdObj*)
declare %QdObj*  @qd_div(%QdObj*, %QdObj*)
declare %QdObj*  @qd_floordiv(%QdObj*, %QdObj*)
declare %QdObj*  @qd_mod(%QdObj*, %QdObj*)
declare %QdObj*  @qd_pow(%QdObj*, %QdObj*)
declare %QdObj*  @qd_neg(%QdObj*)
declare %QdObj*  @qd_not(%QdObj*)
declare %QdObj*  @qd_bitand(%QdObj*, %QdObj*)
declare %QdObj*  @qd_bitor(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_eq(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_ne(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_lt(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_le(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_gt(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_ge(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_is(%QdObj*, %QdObj*)
declare %QdObj*  @qd_getattr(%QdObj*, i8*)
declare void      @qd_setattr(%QdObj*, i8*, %QdObj*)
declare %QdObj*  @qd_getitem(%QdObj*, %QdObj*)
declare void      @qd_setitem(%QdObj*, %QdObj*, %QdObj*)
declare void      @qd_list_append(%QdObj*, %QdObj*)
declare %QdIter* @qd_iter_new(%QdObj*)
declare %QdObj*  @qd_iter_next(%QdIter*)
declare i32       @qd_iter_done(%QdIter*)
declare %QdObj*  @qd_call(%QdObj*, %QdObj**, i32)
declare i32       @qd_truthy(%QdObj*)
declare void      @qd_print(%QdObj*)
declare void      @qd_env_init()
declare void      @qd_env_set(i8*, %QdObj*)
declare %QdObj*  @qd_env_get(i8*)
declare void      @exit(i32) noreturn

@.str.0 = private unnamed_addr constant [3 x i8] c"t0\00"
@.str.1 = private unnamed_addr constant [2 x i8] c"i\00"
@.str.2 = private unnamed_addr constant [4 x i8] c"L_0\00"
@.str.3 = private unnamed_addr constant [3 x i8] c"t1\00"
@.str.4 = private unnamed_addr constant [3 x i8] c"t2\00"
@.str.5 = private unnamed_addr constant [3 x i8] c"t3\00"
@.str.6 = private unnamed_addr constant [4 x i8] c"L_1\00"
@.str.7 = private unnamed_addr constant [3 x i8] c"t4\00"
@.str.8 = private unnamed_addr constant [3 x i8] c"t5\00"
@.str.9 = private unnamed_addr constant [3 x i8] c"t6\00"
@.str.10 = private unnamed_addr constant [3 x i8] c"t7\00"
@.str.11 = private unnamed_addr constant [6 x i8] c"print\00"
@.str.12 = private unnamed_addr constant [3 x i8] c"t8\00"
@.str.13 = private unnamed_addr constant [3 x i8] c"t9\00"

define %QdObj* @main() {
entry:
  call void @qd_env_init()

  %t0_slot = alloca %QdObj*
  %i_slot = alloca %QdObj*
  %t1_slot = alloca %QdObj*
  %t2_slot = alloca %QdObj*
  %t3_slot = alloca %QdObj*
  %L_1_slot = alloca %QdObj*
  %t4_slot = alloca %QdObj*
  %t5_slot = alloca %QdObj*
  %t6_slot = alloca %QdObj*
  %t7_slot = alloca %QdObj*
  %t8_slot = alloca %QdObj*
  %t9_slot = alloca %QdObj*

  %_v0 = call %QdObj* @qd_int(i64 0)
  store %QdObj* %_v0, %QdObj** %t0_slot
  %_v1 = load %QdObj*, %QdObj** %t0_slot
  store %QdObj* %_v1, %QdObj** %i_slot
  %_cs2 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.1, i32 0, i32 0
  call void @qd_env_set(i8* %_cs2, %QdObj* %_v1)
  br label %L_0

L_0:
  %_cs3 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.1, i32 0, i32 0
  %_ln4 = call %QdObj* @qd_env_get(i8* %_cs3)
  store %QdObj* %_ln4, %QdObj** %t1_slot
  %_v5 = call %QdObj* @qd_int(i64 3)
  store %QdObj* %_v5, %QdObj** %t2_slot
  %_v6 = load %QdObj*, %QdObj** %t1_slot
  %_v7 = load %QdObj*, %QdObj** %t2_slot
  %_cm8 = call %QdObj* @qd_cmp_lt(%QdObj* %_v6, %QdObj* %_v7)
  store %QdObj* %_cm8, %QdObj** %t3_slot
  %_v9 = load %QdObj*, %QdObj** %t3_slot
  %_bt10 = call i32 @qd_truthy(%QdObj* %_v9)
  %_bc11 = icmp ne i32 %_bt10, 0
  br i1 %_bc11, label %_fall12, label %L_1

_fall12:
  %_cs13 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.1, i32 0, i32 0
  %_ln14 = call %QdObj* @qd_env_get(i8* %_cs13)
  store %QdObj* %_ln14, %QdObj** %t4_slot
  %_v15 = call %QdObj* @qd_int(i64 1)
  store %QdObj* %_v15, %QdObj** %t5_slot
  %_v16 = load %QdObj*, %QdObj** %t4_slot
  %_v17 = load %QdObj*, %QdObj** %t5_slot
  %_ar18 = call %QdObj* @qd_add(%QdObj* %_v16, %QdObj* %_v17)
  store %QdObj* %_ar18, %QdObj** %t6_slot
  %_v19 = load %QdObj*, %QdObj** %t6_slot
  store %QdObj* %_v19, %QdObj** %i_slot
  %_cs20 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.1, i32 0, i32 0
  call void @qd_env_set(i8* %_cs20, %QdObj* %_v19)
  br label %L_0

L_1:
  %_cs21 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.1, i32 0, i32 0
  %_ln22 = call %QdObj* @qd_env_get(i8* %_cs21)
  store %QdObj* %_ln22, %QdObj** %t7_slot
  %_v23 = load %QdObj*, %QdObj** %t7_slot
  %_cs24 = getelementptr inbounds [6 x i8], [6 x i8]* @.str.11, i32 0, i32 0
  %_ln25 = call %QdObj* @qd_env_get(i8* %_cs24)
  store %QdObj* %_ln25, %QdObj** %t8_slot
  %_v26 = load %QdObj*, %QdObj** %t8_slot
  %_argv27 = alloca %QdObj*, i32 1
  %_ap28 = getelementptr %QdObj*, %QdObj** %_argv27, i32 0
  store %QdObj* %_v23, %QdObj** %_ap28
  %_cr29 = call %QdObj* @qd_call(%QdObj* %_v26, %QdObj** %_argv27, i32 1)
  store %QdObj* %_cr29, %QdObj** %t9_slot

  ret %QdObj* zeroinitializer
}
