; generated by qd0c from ../../py0/py0c/test_while2.qd
source_filename = "../../py0/py0c/test_while2.qd"

; ---- qd0lib 宣告 ----
%QdObj  = type opaque
%QdIter = type opaque

declare %QdObj*  @qd_none()
declare %QdObj*  @qd_bool(i32)
declare %QdObj*  @qd_int(i64)
declare %QdObj*  @qd_float(double)
declare %QdObj*  @qd_string(i8*)
declare %QdObj*  @qd_list_new()
declare %QdObj*  @qd_map_new()
declare %QdObj*  @qd_add(%QdObj*, %QdObj*)
declare %QdObj*  @qd_sub(%QdObj*, %QdObj*)
declare %QdObj*  @qd_mul(%QdObj*, %QdObj*)
declare %QdObj*  @qd_div(%QdObj*, %QdObj*)
declare %QdObj*  @qd_floordiv(%QdObj*, %QdObj*)
declare %QdObj*  @qd_mod(%QdObj*, %QdObj*)
declare %QdObj*  @qd_pow(%QdObj*, %QdObj*)
declare %QdObj*  @qd_neg(%QdObj*)
declare %QdObj*  @qd_not(%QdObj*)
declare %QdObj*  @qd_bitand(%QdObj*, %QdObj*)
declare %QdObj*  @qd_bitor(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_eq(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_ne(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_lt(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_le(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_gt(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_ge(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_is(%QdObj*, %QdObj*)
declare %QdObj*  @qd_getattr(%QdObj*, i8*)
declare void      @qd_setattr(%QdObj*, i8*, %QdObj*)
declare %QdObj*  @qd_getitem(%QdObj*, %QdObj*)
declare void      @qd_setitem(%QdObj*, %QdObj*, %QdObj*)
declare void      @qd_list_append(%QdObj*, %QdObj*)
declare %QdIter* @qd_iter_new(%QdObj*)
declare %QdObj*  @qd_iter_next(%QdIter*)
declare i32       @qd_iter_done(%QdIter*)
declare %QdObj*  @qd_call(%QdObj*, %QdObj**, i32)
declare i32       @qd_truthy(%QdObj*)
declare void      @qd_print(%QdObj*)
declare void      @qd_env_init()
declare void      @qd_env_set(i8*, %QdObj*)
declare %QdObj*  @qd_env_get(i8*)
declare void      @exit(i32) noreturn

@.str.0 = private unnamed_addr constant [3 x i8] c"t0\00"
@.str.1 = private unnamed_addr constant [2 x i8] c"i\00"
@.str.2 = private unnamed_addr constant [3 x i8] c"t1\00"
@.str.3 = private unnamed_addr constant [4 x i8] c"sum\00"
@.str.4 = private unnamed_addr constant [4 x i8] c"L_0\00"
@.str.5 = private unnamed_addr constant [3 x i8] c"t2\00"
@.str.6 = private unnamed_addr constant [3 x i8] c"t3\00"
@.str.7 = private unnamed_addr constant [3 x i8] c"t4\00"
@.str.8 = private unnamed_addr constant [4 x i8] c"L_1\00"
@.str.9 = private unnamed_addr constant [3 x i8] c"t5\00"
@.str.10 = private unnamed_addr constant [3 x i8] c"t6\00"
@.str.11 = private unnamed_addr constant [3 x i8] c"t7\00"
@.str.12 = private unnamed_addr constant [3 x i8] c"t8\00"
@.str.13 = private unnamed_addr constant [6 x i8] c"print\00"
@.str.14 = private unnamed_addr constant [3 x i8] c"t9\00"
@.str.15 = private unnamed_addr constant [4 x i8] c"t10\00"

define %QdObj* @main() {
entry:
  call void @qd_env_init()

  %t0_slot = alloca %QdObj*
  %i_slot = alloca %QdObj*
  %t1_slot = alloca %QdObj*
  %sum_slot = alloca %QdObj*
  %t2_slot = alloca %QdObj*
  %t3_slot = alloca %QdObj*
  %t4_slot = alloca %QdObj*
  %L_1_slot = alloca %QdObj*
  %t5_slot = alloca %QdObj*
  %t6_slot = alloca %QdObj*
  %t7_slot = alloca %QdObj*
  %t8_slot = alloca %QdObj*
  %t9_slot = alloca %QdObj*
  %t10_slot = alloca %QdObj*

  %_v0 = call %QdObj* @qd_int(i64 0)
  store %QdObj* %_v0, %QdObj** %t0_slot
  %_v1 = load %QdObj*, %QdObj** %t0_slot
  store %QdObj* %_v1, %QdObj** %i_slot
  %_cs2 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.1, i32 0, i32 0
  call void @qd_env_set(i8* %_cs2, %QdObj* %_v1)
  %_v3 = call %QdObj* @qd_int(i64 0)
  store %QdObj* %_v3, %QdObj** %t1_slot
  %_v4 = load %QdObj*, %QdObj** %t1_slot
  store %QdObj* %_v4, %QdObj** %sum_slot
  %_cs5 = getelementptr inbounds [4 x i8], [4 x i8]* @.str.3, i32 0, i32 0
  call void @qd_env_set(i8* %_cs5, %QdObj* %_v4)
  br label %L_0

L_0:
  %_cs6 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.1, i32 0, i32 0
  %_ln7 = call %QdObj* @qd_env_get(i8* %_cs6)
  store %QdObj* %_ln7, %QdObj** %t2_slot
  %_v8 = call %QdObj* @qd_int(i64 5)
  store %QdObj* %_v8, %QdObj** %t3_slot
  %_v9 = load %QdObj*, %QdObj** %t2_slot
  %_v10 = load %QdObj*, %QdObj** %t3_slot
  %_cm11 = call %QdObj* @qd_cmp_lt(%QdObj* %_v9, %QdObj* %_v10)
  store %QdObj* %_cm11, %QdObj** %t4_slot
  %_v12 = load %QdObj*, %QdObj** %t4_slot
  %_bt13 = call i32 @qd_truthy(%QdObj* %_v12)
  %_bc14 = icmp ne i32 %_bt13, 0
  br i1 %_bc14, label %_fall15, label %L_1

_fall15:
  %_cs16 = getelementptr inbounds [4 x i8], [4 x i8]* @.str.3, i32 0, i32 0
  %_ln17 = call %QdObj* @qd_env_get(i8* %_cs16)
  store %QdObj* %_ln17, %QdObj** %t5_slot
  %_cs18 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.1, i32 0, i32 0
  %_ln19 = call %QdObj* @qd_env_get(i8* %_cs18)
  store %QdObj* %_ln19, %QdObj** %t6_slot
  %_v20 = load %QdObj*, %QdObj** %t5_slot
  %_v21 = load %QdObj*, %QdObj** %t6_slot
  %_ar22 = call %QdObj* @qd_add(%QdObj* %_v20, %QdObj* %_v21)
  store %QdObj* %_ar22, %QdObj** %t7_slot
  %_v23 = load %QdObj*, %QdObj** %t7_slot
  store %QdObj* %_v23, %QdObj** %sum_slot
  %_cs24 = getelementptr inbounds [4 x i8], [4 x i8]* @.str.3, i32 0, i32 0
  call void @qd_env_set(i8* %_cs24, %QdObj* %_v23)
  br label %L_0

L_1:
  %_cs25 = getelementptr inbounds [4 x i8], [4 x i8]* @.str.3, i32 0, i32 0
  %_ln26 = call %QdObj* @qd_env_get(i8* %_cs25)
  store %QdObj* %_ln26, %QdObj** %t8_slot
  %_v27 = load %QdObj*, %QdObj** %t8_slot
  %_cs28 = getelementptr inbounds [6 x i8], [6 x i8]* @.str.13, i32 0, i32 0
  %_ln29 = call %QdObj* @qd_env_get(i8* %_cs28)
  store %QdObj* %_ln29, %QdObj** %t9_slot
  %_v30 = load %QdObj*, %QdObj** %t9_slot
  %_argv31 = alloca %QdObj*, i32 1
  %_ap32 = getelementptr %QdObj*, %QdObj** %_argv31, i32 0
  store %QdObj* %_v27, %QdObj** %_ap32
  %_cr33 = call %QdObj* @qd_call(%QdObj* %_v30, %QdObj** %_argv31, i32 1)
  store %QdObj* %_cr33, %QdObj** %t10_slot

  ret %QdObj* zeroinitializer
}
