; generated by qd0c from ../../py0/py0c/test_fib.qd
source_filename = "../../py0/py0c/test_fib.qd"

; ---- qd0lib 宣告 ----
%QdObj  = type opaque
%QdIter = type opaque

declare %QdObj*  @qd_none()
declare %QdObj*  @qd_bool(i32)
declare %QdObj*  @qd_int(i64)
declare %QdObj*  @qd_float(double)
declare %QdObj*  @qd_string(i8*)
declare %QdObj*  @qd_list_new()
declare %QdObj*  @qd_map_new()
declare %QdObj*  @qd_add(%QdObj*, %QdObj*)
declare %QdObj*  @qd_sub(%QdObj*, %QdObj*)
declare %QdObj*  @qd_mul(%QdObj*, %QdObj*)
declare %QdObj*  @qd_div(%QdObj*, %QdObj*)
declare %QdObj*  @qd_floordiv(%QdObj*, %QdObj*)
declare %QdObj*  @qd_mod(%QdObj*, %QdObj*)
declare %QdObj*  @qd_pow(%QdObj*, %QdObj*)
declare %QdObj*  @qd_neg(%QdObj*)
declare %QdObj*  @qd_not(%QdObj*)
declare %QdObj*  @qd_bitand(%QdObj*, %QdObj*)
declare %QdObj*  @qd_bitor(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_eq(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_ne(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_lt(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_le(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_gt(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_ge(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_is(%QdObj*, %QdObj*)
declare %QdObj*  @qd_getattr(%QdObj*, i8*)
declare void      @qd_setattr(%QdObj*, i8*, %QdObj*)
declare %QdObj*  @qd_getitem(%QdObj*, %QdObj*)
declare void      @qd_setitem(%QdObj*, %QdObj*, %QdObj*)
declare void      @qd_list_append(%QdObj*, %QdObj*)
declare %QdIter* @qd_iter_new(%QdObj*)
declare %QdObj*  @qd_iter_next(%QdIter*)
declare i32       @qd_iter_done(%QdIter*)
declare %QdObj*  @qd_call(%QdObj*, %QdObj**, i32)
declare i32       @qd_truthy(%QdObj*)
declare void      @qd_print(%QdObj*)
declare void      @qd_env_init()
declare void      @qd_env_set(i8*, %QdObj*)
declare %QdObj*  @qd_env_get(i8*)
declare void      @exit(i32) noreturn

@.str.0 = private unnamed_addr constant [4 x i8] c"fib\00"
@.str.1 = private unnamed_addr constant [2 x i8] c"n\00"
@.str.2 = private unnamed_addr constant [3 x i8] c"t0\00"
@.str.3 = private unnamed_addr constant [3 x i8] c"t1\00"
@.str.4 = private unnamed_addr constant [3 x i8] c"t2\00"
@.str.5 = private unnamed_addr constant [4 x i8] c"L_0\00"
@.str.6 = private unnamed_addr constant [3 x i8] c"t3\00"
@.str.7 = private unnamed_addr constant [4 x i8] c"L_1\00"
@.str.8 = private unnamed_addr constant [3 x i8] c"t4\00"
@.str.9 = private unnamed_addr constant [3 x i8] c"t5\00"
@.str.10 = private unnamed_addr constant [3 x i8] c"t6\00"
@.str.11 = private unnamed_addr constant [3 x i8] c"t7\00"
@.str.12 = private unnamed_addr constant [3 x i8] c"t8\00"
@.str.13 = private unnamed_addr constant [3 x i8] c"t9\00"
@.str.14 = private unnamed_addr constant [4 x i8] c"t10\00"
@.str.15 = private unnamed_addr constant [4 x i8] c"t11\00"
@.str.16 = private unnamed_addr constant [4 x i8] c"t12\00"
@.str.17 = private unnamed_addr constant [4 x i8] c"t13\00"
@.str.18 = private unnamed_addr constant [4 x i8] c"t14\00"
@.str.19 = private unnamed_addr constant [4 x i8] c"t15\00"
@.str.20 = private unnamed_addr constant [4 x i8] c"t16\00"
@.str.21 = private unnamed_addr constant [4 x i8] c"t17\00"
@.str.22 = private unnamed_addr constant [7 x i8] c"result\00"
@.str.23 = private unnamed_addr constant [4 x i8] c"t18\00"
@.str.24 = private unnamed_addr constant [6 x i8] c"print\00"
@.str.25 = private unnamed_addr constant [4 x i8] c"t19\00"
@.str.26 = private unnamed_addr constant [4 x i8] c"t20\00"

define %QdObj* @main() {
entry:
  call void @qd_env_init()

  %t0_slot = alloca %QdObj*
  %t1_slot = alloca %QdObj*
  %t2_slot = alloca %QdObj*
  %L_0_slot = alloca %QdObj*
  %t3_slot = alloca %QdObj*
  %t4_slot = alloca %QdObj*
  %t5_slot = alloca %QdObj*
  %t6_slot = alloca %QdObj*
  %t7_slot = alloca %QdObj*
  %t8_slot = alloca %QdObj*
  %t9_slot = alloca %QdObj*
  %t10_slot = alloca %QdObj*
  %t11_slot = alloca %QdObj*
  %t12_slot = alloca %QdObj*
  %t13_slot = alloca %QdObj*
  %t14_slot = alloca %QdObj*
  %t15_slot = alloca %QdObj*
  %t16_slot = alloca %QdObj*
  %t17_slot = alloca %QdObj*
  %result_slot = alloca %QdObj*
  %t18_slot = alloca %QdObj*
  %t19_slot = alloca %QdObj*
  %t20_slot = alloca %QdObj*

  br label %fib

fib:
  %_cs0 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.1, i32 0, i32 0
  %_ln1 = call %QdObj* @qd_env_get(i8* %_cs0)
  store %QdObj* %_ln1, %QdObj** %t0_slot
  %_v2 = call %QdObj* @qd_int(i64 1)
  store %QdObj* %_v2, %QdObj** %t1_slot
  %_v3 = load %QdObj*, %QdObj** %t0_slot
  %_v4 = load %QdObj*, %QdObj** %t1_slot
  %_cm5 = call %QdObj* @qd_cmp_le(%QdObj* %_v3, %QdObj* %_v4)
  store %QdObj* %_cm5, %QdObj** %t2_slot
  %_v6 = load %QdObj*, %QdObj** %t2_slot
  %_bt7 = call i32 @qd_truthy(%QdObj* %_v6)
  %_bc8 = icmp ne i32 %_bt7, 0
  br i1 %_bc8, label %_fall9, label %L_0

_fall9:
  %_cs10 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.1, i32 0, i32 0
  %_ln11 = call %QdObj* @qd_env_get(i8* %_cs10)
  store %QdObj* %_ln11, %QdObj** %t3_slot
  %_v12 = load %QdObj*, %QdObj** %t3_slot
  ret %QdObj* %_v12
  br label %L_1

L_0:
  %_cs13 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.1, i32 0, i32 0
  %_ln14 = call %QdObj* @qd_env_get(i8* %_cs13)
  store %QdObj* %_ln14, %QdObj** %t4_slot
  %_v15 = call %QdObj* @qd_int(i64 1)
  store %QdObj* %_v15, %QdObj** %t5_slot
  %_v16 = load %QdObj*, %QdObj** %t4_slot
  %_v17 = load %QdObj*, %QdObj** %t5_slot
  %_ar18 = call %QdObj* @qd_sub(%QdObj* %_v16, %QdObj* %_v17)
  store %QdObj* %_ar18, %QdObj** %t6_slot
  %_v19 = load %QdObj*, %QdObj** %t6_slot
  %_cs20 = getelementptr inbounds [4 x i8], [4 x i8]* @.str.0, i32 0, i32 0
  %_ln21 = call %QdObj* @qd_env_get(i8* %_cs20)
  store %QdObj* %_ln21, %QdObj** %t7_slot
  %_v22 = load %QdObj*, %QdObj** %t7_slot
  %_argv23 = alloca %QdObj*, i32 1
  %_ap24 = getelementptr %QdObj*, %QdObj** %_argv23, i32 0
  store %QdObj* %_v19, %QdObj** %_ap24
  %_cr25 = call %QdObj* @qd_call(%QdObj* %_v22, %QdObj** %_argv23, i32 1)
  store %QdObj* %_cr25, %QdObj** %t8_slot
  %_cs26 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.1, i32 0, i32 0
  %_ln27 = call %QdObj* @qd_env_get(i8* %_cs26)
  store %QdObj* %_ln27, %QdObj** %t9_slot
  %_v28 = call %QdObj* @qd_int(i64 2)
  store %QdObj* %_v28, %QdObj** %t10_slot
  %_v29 = load %QdObj*, %QdObj** %t9_slot
  %_v30 = load %QdObj*, %QdObj** %t10_slot
  %_ar31 = call %QdObj* @qd_sub(%QdObj* %_v29, %QdObj* %_v30)
  store %QdObj* %_ar31, %QdObj** %t11_slot
  %_v32 = load %QdObj*, %QdObj** %t11_slot
  %_cs33 = getelementptr inbounds [4 x i8], [4 x i8]* @.str.0, i32 0, i32 0
  %_ln34 = call %QdObj* @qd_env_get(i8* %_cs33)
  store %QdObj* %_ln34, %QdObj** %t12_slot
  %_v35 = load %QdObj*, %QdObj** %t12_slot
  %_argv36 = alloca %QdObj*, i32 1
  %_ap37 = getelementptr %QdObj*, %QdObj** %_argv36, i32 0
  store %QdObj* %_v32, %QdObj** %_ap37
  %_cr38 = call %QdObj* @qd_call(%QdObj* %_v35, %QdObj** %_argv36, i32 1)
  store %QdObj* %_cr38, %QdObj** %t13_slot
  %_v39 = load %QdObj*, %QdObj** %t8_slot
  %_v40 = load %QdObj*, %QdObj** %t13_slot
  %_ar41 = call %QdObj* @qd_add(%QdObj* %_v39, %QdObj* %_v40)
  store %QdObj* %_ar41, %QdObj** %t14_slot
  %_v42 = load %QdObj*, %QdObj** %t14_slot
  ret %QdObj* %_v42

L_1:
  %_v43 = call %QdObj* @qd_int(i64 10)
  store %QdObj* %_v43, %QdObj** %t15_slot
  %_v44 = load %QdObj*, %QdObj** %t15_slot
  %_cs45 = getelementptr inbounds [4 x i8], [4 x i8]* @.str.0, i32 0, i32 0
  %_ln46 = call %QdObj* @qd_env_get(i8* %_cs45)
  store %QdObj* %_ln46, %QdObj** %t16_slot
  %_v47 = load %QdObj*, %QdObj** %t16_slot
  %_argv48 = alloca %QdObj*, i32 1
  %_ap49 = getelementptr %QdObj*, %QdObj** %_argv48, i32 0
  store %QdObj* %_v44, %QdObj** %_ap49
  %_cr50 = call %QdObj* @qd_call(%QdObj* %_v47, %QdObj** %_argv48, i32 1)
  store %QdObj* %_cr50, %QdObj** %t17_slot
  %_v51 = load %QdObj*, %QdObj** %t17_slot
  store %QdObj* %_v51, %QdObj** %result_slot
  %_cs52 = getelementptr inbounds [7 x i8], [7 x i8]* @.str.22, i32 0, i32 0
  call void @qd_env_set(i8* %_cs52, %QdObj* %_v51)
  %_cs53 = getelementptr inbounds [7 x i8], [7 x i8]* @.str.22, i32 0, i32 0
  %_ln54 = call %QdObj* @qd_env_get(i8* %_cs53)
  store %QdObj* %_ln54, %QdObj** %t18_slot
  %_v55 = load %QdObj*, %QdObj** %t18_slot
  %_cs56 = getelementptr inbounds [6 x i8], [6 x i8]* @.str.24, i32 0, i32 0
  %_ln57 = call %QdObj* @qd_env_get(i8* %_cs56)
  store %QdObj* %_ln57, %QdObj** %t19_slot
  %_v58 = load %QdObj*, %QdObj** %t19_slot
  %_argv59 = alloca %QdObj*, i32 1
  %_ap60 = getelementptr %QdObj*, %QdObj** %_argv59, i32 0
  store %QdObj* %_v55, %QdObj** %_ap60
  %_cr61 = call %QdObj* @qd_call(%QdObj* %_v58, %QdObj** %_argv59, i32 1)
  store %QdObj* %_cr61, %QdObj** %t20_slot

  ret %QdObj* zeroinitializer
}
