; generated by qd0c from /Users/Shared/ccc/c0computer/compiler/py0/py0c/test_bool.qd
source_filename = "/Users/Shared/ccc/c0computer/compiler/py0/py0c/test_bool.qd"

; ---- qd0lib 宣告 ----
%QdObj  = type opaque
%QdIter = type opaque

declare %QdObj*  @qd_none()
declare %QdObj*  @qd_bool(i32)
declare %QdObj*  @qd_int(i64)
declare %QdObj*  @qd_float(double)
declare %QdObj*  @qd_string(i8*)
declare %QdObj*  @qd_list_new()
declare %QdObj*  @qd_map_new()
declare %QdObj*  @qd_add(%QdObj*, %QdObj*)
declare %QdObj*  @qd_sub(%QdObj*, %QdObj*)
declare %QdObj*  @qd_mul(%QdObj*, %QdObj*)
declare %QdObj*  @qd_div(%QdObj*, %QdObj*)
declare %QdObj*  @qd_floordiv(%QdObj*, %QdObj*)
declare %QdObj*  @qd_mod(%QdObj*, %QdObj*)
declare %QdObj*  @qd_pow(%QdObj*, %QdObj*)
declare %QdObj*  @qd_neg(%QdObj*)
declare %QdObj*  @qd_not(%QdObj*)
declare %QdObj*  @qd_bitand(%QdObj*, %QdObj*)
declare %QdObj*  @qd_bitor(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_eq(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_ne(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_lt(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_le(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_gt(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_ge(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_is(%QdObj*, %QdObj*)
declare %QdObj*  @qd_getattr(%QdObj*, i8*)
declare void      @qd_setattr(%QdObj*, i8*, %QdObj*)
declare %QdObj*  @qd_getitem(%QdObj*, %QdObj*)
declare void      @qd_setitem(%QdObj*, %QdObj*, %QdObj*)
declare void      @qd_list_append(%QdObj*, %QdObj*)
declare %QdIter* @qd_iter_new(%QdObj*)
declare %QdObj*  @qd_iter_next(%QdIter*)
declare i32       @qd_iter_done(%QdIter*)
declare %QdObj*  @qd_call(%QdObj*, %QdObj**, i32)
declare i32       @qd_truthy(%QdObj*)
declare void      @qd_print(%QdObj*)
declare void      @qd_env_init()
declare void      @qd_env_set(i8*, %QdObj*)
declare %QdObj*  @qd_env_get(i8*)
declare void      @exit(i32) noreturn

@.str.0 = private unnamed_addr constant [3 x i8] c"t0\00"
@.str.1 = private unnamed_addr constant [2 x i8] c"x\00"
@.str.2 = private unnamed_addr constant [3 x i8] c"t1\00"
@.str.3 = private unnamed_addr constant [2 x i8] c"y\00"
@.str.4 = private unnamed_addr constant [3 x i8] c"t2\00"
@.str.5 = private unnamed_addr constant [2 x i8] c"z\00"
@.str.6 = private unnamed_addr constant [3 x i8] c"t3\00"
@.str.7 = private unnamed_addr constant [3 x i8] c"t4\00"
@.str.8 = private unnamed_addr constant [3 x i8] c"t5\00"
@.str.9 = private unnamed_addr constant [3 x i8] c"t6\00"
@.str.10 = private unnamed_addr constant [3 x i8] c"t7\00"
@.str.11 = private unnamed_addr constant [3 x i8] c"t8\00"
@.str.12 = private unnamed_addr constant [3 x i8] c"t9\00"
@.str.13 = private unnamed_addr constant [4 x i8] c"L_0\00"
@.str.14 = private unnamed_addr constant [14 x i8] c"and test pass\00"
@.str.15 = private unnamed_addr constant [4 x i8] c"t10\00"
@.str.16 = private unnamed_addr constant [6 x i8] c"print\00"
@.str.17 = private unnamed_addr constant [4 x i8] c"t11\00"
@.str.18 = private unnamed_addr constant [4 x i8] c"t12\00"
@.str.19 = private unnamed_addr constant [4 x i8] c"L_1\00"
@.str.20 = private unnamed_addr constant [4 x i8] c"t13\00"
@.str.21 = private unnamed_addr constant [4 x i8] c"t14\00"
@.str.22 = private unnamed_addr constant [4 x i8] c"t15\00"
@.str.23 = private unnamed_addr constant [4 x i8] c"t16\00"
@.str.24 = private unnamed_addr constant [4 x i8] c"L_2\00"
@.str.25 = private unnamed_addr constant [14 x i8] c"not test pass\00"
@.str.26 = private unnamed_addr constant [4 x i8] c"t17\00"
@.str.27 = private unnamed_addr constant [4 x i8] c"t18\00"
@.str.28 = private unnamed_addr constant [4 x i8] c"t19\00"
@.str.29 = private unnamed_addr constant [4 x i8] c"L_3\00"
@.str.30 = private unnamed_addr constant [4 x i8] c"t20\00"
@.str.31 = private unnamed_addr constant [4 x i8] c"t21\00"
@.str.32 = private unnamed_addr constant [4 x i8] c"t22\00"
@.str.33 = private unnamed_addr constant [4 x i8] c"t23\00"
@.str.34 = private unnamed_addr constant [4 x i8] c"t24\00"
@.str.35 = private unnamed_addr constant [4 x i8] c"t25\00"
@.str.36 = private unnamed_addr constant [4 x i8] c"t26\00"
@.str.37 = private unnamed_addr constant [4 x i8] c"L_4\00"
@.str.38 = private unnamed_addr constant [13 x i8] c"or test pass\00"
@.str.39 = private unnamed_addr constant [4 x i8] c"t27\00"
@.str.40 = private unnamed_addr constant [4 x i8] c"t28\00"
@.str.41 = private unnamed_addr constant [4 x i8] c"t29\00"
@.str.42 = private unnamed_addr constant [4 x i8] c"L_5\00"
@.str.43 = private unnamed_addr constant [4 x i8] c"t30\00"
@.str.44 = private unnamed_addr constant [4 x i8] c"t31\00"
@.str.45 = private unnamed_addr constant [4 x i8] c"t32\00"
@.str.46 = private unnamed_addr constant [4 x i8] c"t33\00"
@.str.47 = private unnamed_addr constant [4 x i8] c"t34\00"
@.str.48 = private unnamed_addr constant [4 x i8] c"t35\00"
@.str.49 = private unnamed_addr constant [4 x i8] c"t36\00"
@.str.50 = private unnamed_addr constant [4 x i8] c"t37\00"
@.str.51 = private unnamed_addr constant [4 x i8] c"t38\00"
@.str.52 = private unnamed_addr constant [4 x i8] c"t39\00"
@.str.53 = private unnamed_addr constant [4 x i8] c"t40\00"
@.str.54 = private unnamed_addr constant [4 x i8] c"L_6\00"
@.str.55 = private unnamed_addr constant [17 x i8] c"chained and pass\00"
@.str.56 = private unnamed_addr constant [4 x i8] c"t41\00"
@.str.57 = private unnamed_addr constant [4 x i8] c"t42\00"
@.str.58 = private unnamed_addr constant [4 x i8] c"t43\00"
@.str.59 = private unnamed_addr constant [4 x i8] c"L_7\00"
@.str.60 = private unnamed_addr constant [4 x i8] c"t44\00"
@.str.61 = private unnamed_addr constant [2 x i8] c"a\00"
@.str.62 = private unnamed_addr constant [4 x i8] c"t45\00"
@.str.63 = private unnamed_addr constant [2 x i8] c"b\00"
@.str.64 = private unnamed_addr constant [4 x i8] c"t46\00"
@.str.65 = private unnamed_addr constant [4 x i8] c"t47\00"
@.str.66 = private unnamed_addr constant [4 x i8] c"t48\00"
@.str.67 = private unnamed_addr constant [4 x i8] c"t49\00"
@.str.68 = private unnamed_addr constant [4 x i8] c"L_8\00"
@.str.69 = private unnamed_addr constant [21 x i8] c"boolean and not pass\00"
@.str.70 = private unnamed_addr constant [4 x i8] c"t50\00"
@.str.71 = private unnamed_addr constant [4 x i8] c"t51\00"
@.str.72 = private unnamed_addr constant [4 x i8] c"t52\00"
@.str.73 = private unnamed_addr constant [4 x i8] c"L_9\00"

define %QdObj* @main() {
entry:
  call void @qd_env_init()

  %t0_slot = alloca %QdObj*
  %x_slot = alloca %QdObj*
  %t1_slot = alloca %QdObj*
  %y_slot = alloca %QdObj*
  %t2_slot = alloca %QdObj*
  %z_slot = alloca %QdObj*
  %t3_slot = alloca %QdObj*
  %t4_slot = alloca %QdObj*
  %t5_slot = alloca %QdObj*
  %t6_slot = alloca %QdObj*
  %t7_slot = alloca %QdObj*
  %t8_slot = alloca %QdObj*
  %t9_slot = alloca %QdObj*
  %L_0_slot = alloca %QdObj*
  %t10_slot = alloca %QdObj*
  %t11_slot = alloca %QdObj*
  %t12_slot = alloca %QdObj*
  %t13_slot = alloca %QdObj*
  %t14_slot = alloca %QdObj*
  %t15_slot = alloca %QdObj*
  %t16_slot = alloca %QdObj*
  %L_2_slot = alloca %QdObj*
  %t17_slot = alloca %QdObj*
  %t18_slot = alloca %QdObj*
  %t19_slot = alloca %QdObj*
  %t20_slot = alloca %QdObj*
  %t21_slot = alloca %QdObj*
  %t22_slot = alloca %QdObj*
  %t23_slot = alloca %QdObj*
  %t24_slot = alloca %QdObj*
  %t25_slot = alloca %QdObj*
  %t26_slot = alloca %QdObj*
  %L_4_slot = alloca %QdObj*
  %t27_slot = alloca %QdObj*
  %t28_slot = alloca %QdObj*
  %t29_slot = alloca %QdObj*
  %t30_slot = alloca %QdObj*
  %t31_slot = alloca %QdObj*
  %t32_slot = alloca %QdObj*
  %t33_slot = alloca %QdObj*
  %t34_slot = alloca %QdObj*
  %t35_slot = alloca %QdObj*
  %t36_slot = alloca %QdObj*
  %t37_slot = alloca %QdObj*
  %t38_slot = alloca %QdObj*
  %t39_slot = alloca %QdObj*
  %t40_slot = alloca %QdObj*
  %L_6_slot = alloca %QdObj*
  %t41_slot = alloca %QdObj*
  %t42_slot = alloca %QdObj*
  %t43_slot = alloca %QdObj*
  %t44_slot = alloca %QdObj*
  %a_slot = alloca %QdObj*
  %t45_slot = alloca %QdObj*
  %b_slot = alloca %QdObj*
  %t46_slot = alloca %QdObj*
  %t47_slot = alloca %QdObj*
  %t48_slot = alloca %QdObj*
  %t49_slot = alloca %QdObj*
  %L_8_slot = alloca %QdObj*
  %t50_slot = alloca %QdObj*
  %t51_slot = alloca %QdObj*
  %t52_slot = alloca %QdObj*

  %_v0 = call %QdObj* @qd_int(i64 10)
  store %QdObj* %_v0, %QdObj** %t0_slot
  %_v1 = load %QdObj*, %QdObj** %t0_slot
  store %QdObj* %_v1, %QdObj** %x_slot
  %_cs2 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.1, i32 0, i32 0
  call void @qd_env_set(i8* %_cs2, %QdObj* %_v1)
  %_v3 = call %QdObj* @qd_int(i64 5)
  store %QdObj* %_v3, %QdObj** %t1_slot
  %_v4 = load %QdObj*, %QdObj** %t1_slot
  store %QdObj* %_v4, %QdObj** %y_slot
  %_cs5 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.3, i32 0, i32 0
  call void @qd_env_set(i8* %_cs5, %QdObj* %_v4)
  %_v6 = call %QdObj* @qd_int(i64 3)
  store %QdObj* %_v6, %QdObj** %t2_slot
  %_v7 = load %QdObj*, %QdObj** %t2_slot
  store %QdObj* %_v7, %QdObj** %z_slot
  %_cs8 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.5, i32 0, i32 0
  call void @qd_env_set(i8* %_cs8, %QdObj* %_v7)
  %_cs9 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.1, i32 0, i32 0
  %_ln10 = call %QdObj* @qd_env_get(i8* %_cs9)
  store %QdObj* %_ln10, %QdObj** %t3_slot
  %_cs11 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.3, i32 0, i32 0
  %_ln12 = call %QdObj* @qd_env_get(i8* %_cs11)
  store %QdObj* %_ln12, %QdObj** %t4_slot
  %_v13 = load %QdObj*, %QdObj** %t3_slot
  %_v14 = load %QdObj*, %QdObj** %t4_slot
  %_cm15 = call %QdObj* @qd_cmp_gt(%QdObj* %_v13, %QdObj* %_v14)
  store %QdObj* %_cm15, %QdObj** %t5_slot
  %_cs16 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.3, i32 0, i32 0
  %_ln17 = call %QdObj* @qd_env_get(i8* %_cs16)
  store %QdObj* %_ln17, %QdObj** %t6_slot
  %_cs18 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.5, i32 0, i32 0
  %_ln19 = call %QdObj* @qd_env_get(i8* %_cs18)
  store %QdObj* %_ln19, %QdObj** %t7_slot
  %_v20 = load %QdObj*, %QdObj** %t6_slot
  %_v21 = load %QdObj*, %QdObj** %t7_slot
  %_cm22 = call %QdObj* @qd_cmp_gt(%QdObj* %_v20, %QdObj* %_v21)
  store %QdObj* %_cm22, %QdObj** %t8_slot
  %_v23 = load %QdObj*, %QdObj** %t5_slot
  %_v24 = load %QdObj*, %QdObj** %t8_slot
  %_ar25 = call %QdObj* @qd_bitand(%QdObj* %_v23, %QdObj* %_v24)
  store %QdObj* %_ar25, %QdObj** %t9_slot
  %_v26 = load %QdObj*, %QdObj** %t9_slot
  %_bt27 = call i32 @qd_truthy(%QdObj* %_v26)
  %_bc28 = icmp ne i32 %_bt27, 0
  br i1 %_bc28, label %_fall29, label %L_0

_fall29:
  %_gp31 = getelementptr inbounds [14 x i8], [14 x i8]* @.str.14, i32 0, i32 0
  %_v30 = call %QdObj* @qd_string(i8* %_gp31)
  store %QdObj* %_v30, %QdObj** %t10_slot
  %_v32 = load %QdObj*, %QdObj** %t10_slot
  %_cs33 = getelementptr inbounds [6 x i8], [6 x i8]* @.str.16, i32 0, i32 0
  %_ln34 = call %QdObj* @qd_env_get(i8* %_cs33)
  store %QdObj* %_ln34, %QdObj** %t11_slot
  %_v35 = load %QdObj*, %QdObj** %t11_slot
  %_argv36 = alloca %QdObj*, i32 1
  %_ap37 = getelementptr %QdObj*, %QdObj** %_argv36, i32 0
  store %QdObj* %_v32, %QdObj** %_ap37
  %_cr38 = call %QdObj* @qd_call(%QdObj* %_v35, %QdObj** %_argv36, i32 1)
  store %QdObj* %_cr38, %QdObj** %t12_slot
  br label %L_1

L_0:
  br label %L_1

L_1:
  %_cs39 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.1, i32 0, i32 0
  %_ln40 = call %QdObj* @qd_env_get(i8* %_cs39)
  store %QdObj* %_ln40, %QdObj** %t13_slot
  %_cs41 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.3, i32 0, i32 0
  %_ln42 = call %QdObj* @qd_env_get(i8* %_cs41)
  store %QdObj* %_ln42, %QdObj** %t14_slot
  %_v43 = load %QdObj*, %QdObj** %t13_slot
  %_v44 = load %QdObj*, %QdObj** %t14_slot
  %_cm45 = call %QdObj* @qd_cmp_lt(%QdObj* %_v43, %QdObj* %_v44)
  store %QdObj* %_cm45, %QdObj** %t15_slot
  %_v46 = load %QdObj*, %QdObj** %t15_slot
  %_un47 = call %QdObj* @qd_not(%QdObj* %_v46)
  store %QdObj* %_un47, %QdObj** %t16_slot
  %_v48 = load %QdObj*, %QdObj** %t16_slot
  %_bt49 = call i32 @qd_truthy(%QdObj* %_v48)
  %_bc50 = icmp ne i32 %_bt49, 0
  br i1 %_bc50, label %_fall51, label %L_2

_fall51:
  %_gp53 = getelementptr inbounds [14 x i8], [14 x i8]* @.str.25, i32 0, i32 0
  %_v52 = call %QdObj* @qd_string(i8* %_gp53)
  store %QdObj* %_v52, %QdObj** %t17_slot
  %_v54 = load %QdObj*, %QdObj** %t17_slot
  %_cs55 = getelementptr inbounds [6 x i8], [6 x i8]* @.str.16, i32 0, i32 0
  %_ln56 = call %QdObj* @qd_env_get(i8* %_cs55)
  store %QdObj* %_ln56, %QdObj** %t18_slot
  %_v57 = load %QdObj*, %QdObj** %t18_slot
  %_argv58 = alloca %QdObj*, i32 1
  %_ap59 = getelementptr %QdObj*, %QdObj** %_argv58, i32 0
  store %QdObj* %_v54, %QdObj** %_ap59
  %_cr60 = call %QdObj* @qd_call(%QdObj* %_v57, %QdObj** %_argv58, i32 1)
  store %QdObj* %_cr60, %QdObj** %t19_slot
  br label %L_3

L_2:
  br label %L_3

L_3:
  %_cs61 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.1, i32 0, i32 0
  %_ln62 = call %QdObj* @qd_env_get(i8* %_cs61)
  store %QdObj* %_ln62, %QdObj** %t20_slot
  %_cs63 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.3, i32 0, i32 0
  %_ln64 = call %QdObj* @qd_env_get(i8* %_cs63)
  store %QdObj* %_ln64, %QdObj** %t21_slot
  %_v65 = load %QdObj*, %QdObj** %t20_slot
  %_v66 = load %QdObj*, %QdObj** %t21_slot
  %_cm67 = call %QdObj* @qd_cmp_gt(%QdObj* %_v65, %QdObj* %_v66)
  store %QdObj* %_cm67, %QdObj** %t22_slot
  %_cs68 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.3, i32 0, i32 0
  %_ln69 = call %QdObj* @qd_env_get(i8* %_cs68)
  store %QdObj* %_ln69, %QdObj** %t23_slot
  %_cs70 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.1, i32 0, i32 0
  %_ln71 = call %QdObj* @qd_env_get(i8* %_cs70)
  store %QdObj* %_ln71, %QdObj** %t24_slot
  %_v72 = load %QdObj*, %QdObj** %t23_slot
  %_v73 = load %QdObj*, %QdObj** %t24_slot
  %_cm74 = call %QdObj* @qd_cmp_gt(%QdObj* %_v72, %QdObj* %_v73)
  store %QdObj* %_cm74, %QdObj** %t25_slot
  %_v75 = load %QdObj*, %QdObj** %t22_slot
  %_v76 = load %QdObj*, %QdObj** %t25_slot
  %_ar77 = call %QdObj* @qd_bitor(%QdObj* %_v75, %QdObj* %_v76)
  store %QdObj* %_ar77, %QdObj** %t26_slot
  %_v78 = load %QdObj*, %QdObj** %t26_slot
  %_bt79 = call i32 @qd_truthy(%QdObj* %_v78)
  %_bc80 = icmp ne i32 %_bt79, 0
  br i1 %_bc80, label %_fall81, label %L_4

_fall81:
  %_gp83 = getelementptr inbounds [13 x i8], [13 x i8]* @.str.38, i32 0, i32 0
  %_v82 = call %QdObj* @qd_string(i8* %_gp83)
  store %QdObj* %_v82, %QdObj** %t27_slot
  %_v84 = load %QdObj*, %QdObj** %t27_slot
  %_cs85 = getelementptr inbounds [6 x i8], [6 x i8]* @.str.16, i32 0, i32 0
  %_ln86 = call %QdObj* @qd_env_get(i8* %_cs85)
  store %QdObj* %_ln86, %QdObj** %t28_slot
  %_v87 = load %QdObj*, %QdObj** %t28_slot
  %_argv88 = alloca %QdObj*, i32 1
  %_ap89 = getelementptr %QdObj*, %QdObj** %_argv88, i32 0
  store %QdObj* %_v84, %QdObj** %_ap89
  %_cr90 = call %QdObj* @qd_call(%QdObj* %_v87, %QdObj** %_argv88, i32 1)
  store %QdObj* %_cr90, %QdObj** %t29_slot
  br label %L_5

L_4:
  br label %L_5

L_5:
  %_cs91 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.1, i32 0, i32 0
  %_ln92 = call %QdObj* @qd_env_get(i8* %_cs91)
  store %QdObj* %_ln92, %QdObj** %t30_slot
  %_cs93 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.3, i32 0, i32 0
  %_ln94 = call %QdObj* @qd_env_get(i8* %_cs93)
  store %QdObj* %_ln94, %QdObj** %t31_slot
  %_v95 = load %QdObj*, %QdObj** %t30_slot
  %_v96 = load %QdObj*, %QdObj** %t31_slot
  %_cm97 = call %QdObj* @qd_cmp_gt(%QdObj* %_v95, %QdObj* %_v96)
  store %QdObj* %_cm97, %QdObj** %t32_slot
  %_cs98 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.3, i32 0, i32 0
  %_ln99 = call %QdObj* @qd_env_get(i8* %_cs98)
  store %QdObj* %_ln99, %QdObj** %t33_slot
  %_cs100 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.5, i32 0, i32 0
  %_ln101 = call %QdObj* @qd_env_get(i8* %_cs100)
  store %QdObj* %_ln101, %QdObj** %t34_slot
  %_v102 = load %QdObj*, %QdObj** %t33_slot
  %_v103 = load %QdObj*, %QdObj** %t34_slot
  %_cm104 = call %QdObj* @qd_cmp_gt(%QdObj* %_v102, %QdObj* %_v103)
  store %QdObj* %_cm104, %QdObj** %t35_slot
  %_v105 = load %QdObj*, %QdObj** %t32_slot
  %_v106 = load %QdObj*, %QdObj** %t35_slot
  %_ar107 = call %QdObj* @qd_bitand(%QdObj* %_v105, %QdObj* %_v106)
  store %QdObj* %_ar107, %QdObj** %t36_slot
  %_cs108 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.5, i32 0, i32 0
  %_ln109 = call %QdObj* @qd_env_get(i8* %_cs108)
  store %QdObj* %_ln109, %QdObj** %t37_slot
  %_v110 = call %QdObj* @qd_int(i64 0)
  store %QdObj* %_v110, %QdObj** %t38_slot
  %_v111 = load %QdObj*, %QdObj** %t37_slot
  %_v112 = load %QdObj*, %QdObj** %t38_slot
  %_cm113 = call %QdObj* @qd_cmp_gt(%QdObj* %_v111, %QdObj* %_v112)
  store %QdObj* %_cm113, %QdObj** %t39_slot
  %_v114 = load %QdObj*, %QdObj** %t36_slot
  %_v115 = load %QdObj*, %QdObj** %t39_slot
  %_ar116 = call %QdObj* @qd_bitand(%QdObj* %_v114, %QdObj* %_v115)
  store %QdObj* %_ar116, %QdObj** %t40_slot
  %_v117 = load %QdObj*, %QdObj** %t40_slot
  %_bt118 = call i32 @qd_truthy(%QdObj* %_v117)
  %_bc119 = icmp ne i32 %_bt118, 0
  br i1 %_bc119, label %_fall120, label %L_6

_fall120:
  %_gp122 = getelementptr inbounds [17 x i8], [17 x i8]* @.str.55, i32 0, i32 0
  %_v121 = call %QdObj* @qd_string(i8* %_gp122)
  store %QdObj* %_v121, %QdObj** %t41_slot
  %_v123 = load %QdObj*, %QdObj** %t41_slot
  %_cs124 = getelementptr inbounds [6 x i8], [6 x i8]* @.str.16, i32 0, i32 0
  %_ln125 = call %QdObj* @qd_env_get(i8* %_cs124)
  store %QdObj* %_ln125, %QdObj** %t42_slot
  %_v126 = load %QdObj*, %QdObj** %t42_slot
  %_argv127 = alloca %QdObj*, i32 1
  %_ap128 = getelementptr %QdObj*, %QdObj** %_argv127, i32 0
  store %QdObj* %_v123, %QdObj** %_ap128
  %_cr129 = call %QdObj* @qd_call(%QdObj* %_v126, %QdObj** %_argv127, i32 1)
  store %QdObj* %_cr129, %QdObj** %t43_slot
  br label %L_7

L_6:
  br label %L_7

L_7:
  %_v130 = call %QdObj* @qd_int(i64 1)
  store %QdObj* %_v130, %QdObj** %t44_slot
  %_v131 = load %QdObj*, %QdObj** %t44_slot
  store %QdObj* %_v131, %QdObj** %a_slot
  %_cs132 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.61, i32 0, i32 0
  call void @qd_env_set(i8* %_cs132, %QdObj* %_v131)
  %_v133 = call %QdObj* @qd_int(i64 0)
  store %QdObj* %_v133, %QdObj** %t45_slot
  %_v134 = load %QdObj*, %QdObj** %t45_slot
  store %QdObj* %_v134, %QdObj** %b_slot
  %_cs135 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.63, i32 0, i32 0
  call void @qd_env_set(i8* %_cs135, %QdObj* %_v134)
  %_cs136 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.61, i32 0, i32 0
  %_ln137 = call %QdObj* @qd_env_get(i8* %_cs136)
  store %QdObj* %_ln137, %QdObj** %t46_slot
  %_cs138 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.63, i32 0, i32 0
  %_ln139 = call %QdObj* @qd_env_get(i8* %_cs138)
  store %QdObj* %_ln139, %QdObj** %t47_slot
  %_v140 = load %QdObj*, %QdObj** %t47_slot
  %_un141 = call %QdObj* @qd_not(%QdObj* %_v140)
  store %QdObj* %_un141, %QdObj** %t48_slot
  %_v142 = load %QdObj*, %QdObj** %t46_slot
  %_v143 = load %QdObj*, %QdObj** %t48_slot
  %_ar144 = call %QdObj* @qd_bitand(%QdObj* %_v142, %QdObj* %_v143)
  store %QdObj* %_ar144, %QdObj** %t49_slot
  %_v145 = load %QdObj*, %QdObj** %t49_slot
  %_bt146 = call i32 @qd_truthy(%QdObj* %_v145)
  %_bc147 = icmp ne i32 %_bt146, 0
  br i1 %_bc147, label %_fall148, label %L_8

_fall148:
  %_gp150 = getelementptr inbounds [21 x i8], [21 x i8]* @.str.69, i32 0, i32 0
  %_v149 = call %QdObj* @qd_string(i8* %_gp150)
  store %QdObj* %_v149, %QdObj** %t50_slot
  %_v151 = load %QdObj*, %QdObj** %t50_slot
  %_cs152 = getelementptr inbounds [6 x i8], [6 x i8]* @.str.16, i32 0, i32 0
  %_ln153 = call %QdObj* @qd_env_get(i8* %_cs152)
  store %QdObj* %_ln153, %QdObj** %t51_slot
  %_v154 = load %QdObj*, %QdObj** %t51_slot
  %_argv155 = alloca %QdObj*, i32 1
  %_ap156 = getelementptr %QdObj*, %QdObj** %_argv155, i32 0
  store %QdObj* %_v151, %QdObj** %_ap156
  %_cr157 = call %QdObj* @qd_call(%QdObj* %_v154, %QdObj** %_argv155, i32 1)
  store %QdObj* %_cr157, %QdObj** %t52_slot
  br label %L_9

L_8:
  br label %L_9

L_9:

  ret %QdObj* zeroinitializer
}
