/* Generated by AST Verilog0C transpiler */
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>

uint8_t clock = 0;
int curr_time = 0;
void eval_all();
void eval_always_posedge();


uint8_t a;
uint8_t b;
uint8_t eq;
uint8_t neq;
uint8_t a;
uint8_t b;
uint8_t eq;
uint8_t neq;

void eval_all() {
    eq = (!(a ^ b));
    neq = (a ^ b);
}

void eval_always_posedge() {
}

int main() {
    {
        a = 0;
        b = 0;
        curr_time += 0;
    eval_all();
        printf("a=%d, b=%d => eq=%d, neq=%d\n", a, b, eq, neq);
        a = 0;
        b = 1;
        curr_time += 0;
    eval_all();
        printf("a=%d, b=%d => eq=%d, neq=%d\n", a, b, eq, neq);
        a = 1;
        b = 0;
        curr_time += 0;
    eval_all();
        printf("a=%d, b=%d => eq=%d, neq=%d\n", a, b, eq, neq);
        a = 1;
        b = 1;
        curr_time += 0;
    eval_all();
        printf("a=%d, b=%d => eq=%d, neq=%d\n", a, b, eq, neq);
    }
    eval_all();
    return 0;
}
