; generated by qd0c from fact.qd
source_filename = "fact.qd"

; ---- qd0lib 宣告 ----
%QdObj  = type opaque
%QdIter = type opaque

declare %QdObj*  @qd_none()
declare %QdObj*  @qd_bool(i32)
declare %QdObj*  @qd_int(i64)
declare %QdObj*  @qd_float(double)
declare %QdObj*  @qd_string(i8*)
declare %QdObj*  @qd_list_new()
declare %QdObj*  @qd_map_new()
declare %QdObj*  @qd_add(%QdObj*, %QdObj*)
declare %QdObj*  @qd_sub(%QdObj*, %QdObj*)
declare %QdObj*  @qd_mul(%QdObj*, %QdObj*)
declare %QdObj*  @qd_div(%QdObj*, %QdObj*)
declare %QdObj*  @qd_floordiv(%QdObj*, %QdObj*)
declare %QdObj*  @qd_mod(%QdObj*, %QdObj*)
declare %QdObj*  @qd_pow(%QdObj*, %QdObj*)
declare %QdObj*  @qd_neg(%QdObj*)
declare %QdObj*  @qd_not(%QdObj*)
declare %QdObj*  @qd_cmp_eq(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_ne(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_lt(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_le(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_gt(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_ge(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_is(%QdObj*, %QdObj*)
declare %QdObj*  @qd_getattr(%QdObj*, i8*)
declare void      @qd_setattr(%QdObj*, i8*, %QdObj*)
declare %QdObj*  @qd_getitem(%QdObj*, %QdObj*)
declare void      @qd_setitem(%QdObj*, %QdObj*, %QdObj*)
declare void      @qd_list_append(%QdObj*, %QdObj*)
declare %QdIter* @qd_iter_new(%QdObj*)
declare %QdObj*  @qd_iter_next(%QdIter*)
declare i32       @qd_iter_done(%QdIter*)
declare %QdObj*  @qd_call(%QdObj*, %QdObj**, i32)
declare i32       @qd_truthy(%QdObj*)
declare void      @qd_print(%QdObj*)
declare void      @qd_env_init()
declare void      @qd_env_set(i8*, %QdObj*)
declare %QdObj*  @qd_env_get(i8*)
declare void      @exit(i32) noreturn

@.str.0 = private unnamed_addr constant [10 x i8] c"factorial\00"
@.str.1 = private unnamed_addr constant [9 x i8] c"function\00"
@.str.2 = private unnamed_addr constant [2 x i8] c"n\00"
@.str.3 = private unnamed_addr constant [3 x i8] c"t0\00"
@.str.4 = private unnamed_addr constant [3 x i8] c"t1\00"
@.str.5 = private unnamed_addr constant [3 x i8] c"t2\00"
@.str.6 = private unnamed_addr constant [7 x i8] c"L_else\00"
@.str.7 = private unnamed_addr constant [3 x i8] c"t3\00"
@.str.8 = private unnamed_addr constant [3 x i8] c"t4\00"
@.str.9 = private unnamed_addr constant [3 x i8] c"t5\00"
@.str.10 = private unnamed_addr constant [3 x i8] c"t6\00"
@.str.11 = private unnamed_addr constant [3 x i8] c"t7\00"
@.str.12 = private unnamed_addr constant [3 x i8] c"t8\00"
@.str.13 = private unnamed_addr constant [3 x i8] c"t9\00"
@.str.14 = private unnamed_addr constant [4 x i8] c"t10\00"
@.str.15 = private unnamed_addr constant [8 x i8] c"program\00"
@.str.16 = private unnamed_addr constant [6 x i8] c"entry\00"
@.str.17 = private unnamed_addr constant [4 x i8] c"t11\00"
@.str.18 = private unnamed_addr constant [4 x i8] c"t12\00"
@.str.19 = private unnamed_addr constant [4 x i8] c"t13\00"
@.str.20 = private unnamed_addr constant [7 x i8] c"result\00"
@.str.21 = private unnamed_addr constant [6 x i8] c"print\00"
@.str.22 = private unnamed_addr constant [4 x i8] c"t14\00"
@.str.23 = private unnamed_addr constant [4 x i8] c"t15\00"
@.str.24 = private unnamed_addr constant [4 x i8] c"t16\00"

define i32 @main() {
entry:
  call void @qd_env_init()

  %t0_slot = alloca %QdObj*
  %t1_slot = alloca %QdObj*
  %t2_slot = alloca %QdObj*
  %L_else_slot = alloca %QdObj*
  %t3_slot = alloca %QdObj*
  %t4_slot = alloca %QdObj*
  %t5_slot = alloca %QdObj*
  %t6_slot = alloca %QdObj*
  %t7_slot = alloca %QdObj*
  %t8_slot = alloca %QdObj*
  %t9_slot = alloca %QdObj*
  %t10_slot = alloca %QdObj*
  %t11_slot = alloca %QdObj*
  %t12_slot = alloca %QdObj*
  %t13_slot = alloca %QdObj*
  %result_slot = alloca %QdObj*
  %t14_slot = alloca %QdObj*
  %t15_slot = alloca %QdObj*
  %t16_slot = alloca %QdObj*

  ; COMMENT factorial function _
  br label %factorial

factorial:
  %_cs1 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.2, i32 0, i32 0
  %_v0 = call %QdObj* @qd_env_get(i8* %_cs1)
  store %QdObj* %_v0, %QdObj** %t0_slot
  %_v2 = call %QdObj* @qd_int(i64 0)
  store %QdObj* %_v2, %QdObj** %t1_slot
  %_v3 = load %QdObj*, %QdObj** %t0_slot
  %_v4 = load %QdObj*, %QdObj** %t1_slot
  %_cm5 = call %QdObj* @qd_cmp_eq(%QdObj* %_v4, %QdObj* %_v4)
  store %QdObj* %_cm5, %QdObj** %t2_slot
  %_v6 = load %QdObj*, %QdObj** %t2_slot
  %_bt7 = call i32 @qd_truthy(%QdObj* %_v6)
  %_bc8 = icmp ne i32 %_bt7, 0
  br i1 %_bc8, label %_fall9, label %L_else

_fall9:
  %_v10 = call %QdObj* @qd_int(i64 1)
  store %QdObj* %_v10, %QdObj** %t3_slot
  %_v11 = load %QdObj*, %QdObj** %t3_slot
  ret %QdObj* %_v11

L_else:
  %_cs13 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.2, i32 0, i32 0
  %_v12 = call %QdObj* @qd_env_get(i8* %_cs13)
  store %QdObj* %_v12, %QdObj** %t4_slot
  %_cs15 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.2, i32 0, i32 0
  %_v14 = call %QdObj* @qd_env_get(i8* %_cs15)
  store %QdObj* %_v14, %QdObj** %t5_slot
  %_v16 = call %QdObj* @qd_int(i64 1)
  store %QdObj* %_v16, %QdObj** %t6_slot
  %_v17 = load %QdObj*, %QdObj** %t5_slot
  %_v18 = load %QdObj*, %QdObj** %t6_slot
  %_ar19 = call %QdObj* @qd_sub(%QdObj* %_v18, %QdObj* %_v18)
  store %QdObj* %_ar19, %QdObj** %t7_slot
  %_cs20 = getelementptr inbounds [10 x i8], [10 x i8]* @.str.0, i32 0, i32 0
  %_ln21 = call %QdObj* @qd_env_get(i8* %_cs20)
  store %QdObj* %_ln21, %QdObj** %t8_slot
  %_v22 = load %QdObj*, %QdObj** %t7_slot
  %_v23 = load %QdObj*, %QdObj** %t8_slot
  %_argv24 = alloca %QdObj*, i32 1
  %_ap25 = getelementptr %QdObj*, %QdObj** %_argv24, i32 0
  store %QdObj* %_v22, %QdObj** %_ap25
  %_cr26 = call %QdObj* @qd_call(%QdObj* %_v23, %QdObj** %_argv24, i32 1)
  store %QdObj* %_cr26, %QdObj** %t9_slot
  %_v27 = load %QdObj*, %QdObj** %t4_slot
  %_v28 = load %QdObj*, %QdObj** %t9_slot
  %_ar29 = call %QdObj* @qd_mul(%QdObj* %_v28, %QdObj* %_v28)
  store %QdObj* %_ar29, %QdObj** %t10_slot
  %_v30 = load %QdObj*, %QdObj** %t10_slot
  ret %QdObj* %_v30
  ; COMMENT program entry _
  %_v31 = call %QdObj* @qd_int(i64 5)
  store %QdObj* %_v31, %QdObj** %t11_slot
  %_cs32 = getelementptr inbounds [10 x i8], [10 x i8]* @.str.0, i32 0, i32 0
  %_ln33 = call %QdObj* @qd_env_get(i8* %_cs32)
  store %QdObj* %_ln33, %QdObj** %t12_slot
  %_v34 = load %QdObj*, %QdObj** %t11_slot
  %_v35 = load %QdObj*, %QdObj** %t12_slot
  %_argv36 = alloca %QdObj*, i32 1
  %_ap37 = getelementptr %QdObj*, %QdObj** %_argv36, i32 0
  store %QdObj* %_v34, %QdObj** %_ap37
  %_cr38 = call %QdObj* @qd_call(%QdObj* %_v35, %QdObj** %_argv36, i32 1)
  store %QdObj* %_cr38, %QdObj** %t13_slot
  %_v39 = load %QdObj*, %QdObj** %t13_slot
  store %QdObj* %_v39, %QdObj** %result_slot
  %_cs40 = getelementptr inbounds [7 x i8], [7 x i8]* @.str.20, i32 0, i32 0
  call void @qd_env_set(i8* %_cs40, %QdObj* %_v39)
  %_cs41 = getelementptr inbounds [6 x i8], [6 x i8]* @.str.21, i32 0, i32 0
  %_ln42 = call %QdObj* @qd_env_get(i8* %_cs41)
  store %QdObj* %_ln42, %QdObj** %t14_slot
  %_cs43 = getelementptr inbounds [7 x i8], [7 x i8]* @.str.20, i32 0, i32 0
  %_ln44 = call %QdObj* @qd_env_get(i8* %_cs43)
  store %QdObj* %_ln44, %QdObj** %t15_slot
  %_v45 = load %QdObj*, %QdObj** %t15_slot
  %_v46 = load %QdObj*, %QdObj** %t14_slot
  %_argv47 = alloca %QdObj*, i32 1
  %_ap48 = getelementptr %QdObj*, %QdObj** %_argv47, i32 0
  store %QdObj* %_v45, %QdObj** %_ap48
  %_cr49 = call %QdObj* @qd_call(%QdObj* %_v46, %QdObj** %_argv47, i32 1)
  store %QdObj* %_cr49, %QdObj** %t16_slot

  ret i32 0
}
