/* Generated by AST Verilog0C transpiler */
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>

uint8_t clock = 0;
int curr_time = 0;
void eval_all();
void eval_always_posedge();


uint8_t a;
uint8_t b;
uint8_t cin;
uint8_t sum;
uint8_t cout;
uint8_t a;
uint8_t b;
uint8_t cin;
uint8_t sum;
uint8_t cout;

void eval_all() {
    sum = ((a ^ b) ^ cin);
    cout = ((a & b) | (cin & (a ^ b)));
}

void eval_always_posedge() {
}

int main() {
    {
        a = 0;
        b = 0;
        cin = 0;
        curr_time += 0;
    eval_all();
        printf("a=%d, b=%d, cin=%d => sum=%d, cout=%d\n", a, b, cin, sum, cout);
        a = 0;
        b = 0;
        cin = 1;
        curr_time += 0;
    eval_all();
        printf("a=%d, b=%d, cin=%d => sum=%d, cout=%d\n", a, b, cin, sum, cout);
        a = 0;
        b = 1;
        cin = 0;
        curr_time += 0;
    eval_all();
        printf("a=%d, b=%d, cin=%d => sum=%d, cout=%d\n", a, b, cin, sum, cout);
        a = 0;
        b = 1;
        cin = 1;
        curr_time += 0;
    eval_all();
        printf("a=%d, b=%d, cin=%d => sum=%d, cout=%d\n", a, b, cin, sum, cout);
        a = 1;
        b = 0;
        cin = 0;
        curr_time += 0;
    eval_all();
        printf("a=%d, b=%d, cin=%d => sum=%d, cout=%d\n", a, b, cin, sum, cout);
        a = 1;
        b = 0;
        cin = 1;
        curr_time += 0;
    eval_all();
        printf("a=%d, b=%d, cin=%d => sum=%d, cout=%d\n", a, b, cin, sum, cout);
        a = 1;
        b = 1;
        cin = 0;
        curr_time += 0;
    eval_all();
        printf("a=%d, b=%d, cin=%d => sum=%d, cout=%d\n", a, b, cin, sum, cout);
        a = 1;
        b = 1;
        cin = 1;
        curr_time += 0;
    eval_all();
        printf("a=%d, b=%d, cin=%d => sum=%d, cout=%d\n", a, b, cin, sum, cout);
    }
    eval_all();
    return 0;
}
