/* Generated by AST Verilog0C transpiler */
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>

uint8_t clock = 0;
int curr_time = 0;
void eval_all();
void eval_always_posedge();

#define N (((SW) >> 15) & 1)
#define Z (((SW) >> 14) & 1)
#define OP (((IR) >> 12) & 0xF)
#define C (((IR) >> 0) & 0xFFF)
#define M ((m[C]<<8) | m[(C + 1)])

enum { LD = 0, ADD = 1, JMP = 2, ST = 3, CMP = 4, JEQ = 5};
int16_t A;
uint16_t IR;
uint16_t SW;
uint16_t PC;
uint16_t pc0;
uint8_t m[33];
int i;
uint8_t clock;

void eval_all() {
}

void eval_always_posedge() {
    {
        IR = ((m[PC]<<8) | m[(PC + 1)]);
        pc0 = PC;
        PC = (PC + 2);
        switch (OP) {
            case LD:
                A = M;
                break;
            case ST:
                m[C] = A >> 8;
    m[C+1] = A & 0xFF;
                break;
            case CMP:
                {
                    SW = (SW & ~0x8000) | ((((A < M)) & 1) << 15);
                    SW = (SW & ~0x4000) | ((((A == M)) & 1) << 14);
                }
                break;
            case ADD:
                A = (A + M);
                break;
            case JMP:
                PC = C;
                break;
            case JEQ:
                if (Z) 
                    PC = C;
                break;
        }
        printf("%4dns PC=%04X IR=%04X, SW=%04X, A=%d\n", curr_time, pc0, IR, SW, A);
    }
}

int main() {
    {
        PC = 0;
        SW = 0;
        {
      int _idx=0; int h1,h2; char _l[256];
      FILE *_f=fopen("mcu0m.hex","r");
      if(_f) while(fgets(_l, 256, _f)){
        if (_l[0]=='/' || _l[0]=='\n') continue;
        if(sscanf(_l,"%x %x",&h1,&h2)==2){ m[_idx++]=h1; m[_idx++]=h2; }
        else if(sscanf(_l,"%x",&h1)==1){ m[_idx++]=h1>>8; m[_idx++]=h1&0xff; }
      }
      if(_f) fclose(_f);
    }
        for (i=0; (i < 32); i=(i + 2)) {
            {
                printf("%8x: %8x\n", i, ((m[i]<<8) | m[(i + 1)]));
            }
        }
    }
    clock = 0;
    curr_time += 000;
    eval_all();
        while(curr_time <= 2000) {
        if(curr_time>0 && curr_time % 10 == 0) {
            clock = !clock;
            if (clock) eval_always_posedge();
        }
        eval_all();
        curr_time += 10;
    }
    return 0;
}
