/* Generated by AST Verilog0C transpiler */
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>

uint8_t clock = 0;
int curr_time = 0;
void eval_all();
void eval_always_posedge();


uint8_t d0;
uint8_t d1;
uint8_t sel;
uint8_t y;
uint8_t d0;
uint8_t d1;
uint8_t sel;
uint8_t y;

void eval_all() {
    y = (((!sel) & d0) | (sel & d1));
}

void eval_always_posedge() {
}

int main() {
    {
        d0 = 0;
        d1 = 1;
        sel = 0;
        curr_time += 0;
    eval_all();
        printf("d0=%d, d1=%d, sel=%d => y=%d\n", d0, d1, sel, y);
        d0 = 0;
        d1 = 1;
        sel = 1;
        curr_time += 0;
    eval_all();
        printf("d0=%d, d1=%d, sel=%d => y=%d\n", d0, d1, sel, y);
        d0 = 1;
        d1 = 0;
        sel = 0;
        curr_time += 0;
    eval_all();
        printf("d0=%d, d1=%d, sel=%d => y=%d\n", d0, d1, sel, y);
        d0 = 1;
        d1 = 0;
        sel = 1;
        curr_time += 0;
    eval_all();
        printf("d0=%d, d1=%d, sel=%d => y=%d\n", d0, d1, sel, y);
    }
    eval_all();
    return 0;
}
