; generated by qd0c from test.qd
source_filename = "test.qd"

; ---- qd0lib 宣告 ----
%QdObj  = type opaque
%QdIter = type opaque

declare %QdObj*  @qd_none()
declare %QdObj*  @qd_bool(i32)
declare %QdObj*  @qd_int(i64)
declare %QdObj*  @qd_float(double)
declare %QdObj*  @qd_string(i8*)
declare %QdObj*  @qd_list_new()
declare %QdObj*  @qd_map_new()
declare %QdObj*  @qd_add(%QdObj*, %QdObj*)
declare %QdObj*  @qd_sub(%QdObj*, %QdObj*)
declare %QdObj*  @qd_mul(%QdObj*, %QdObj*)
declare %QdObj*  @qd_div(%QdObj*, %QdObj*)
declare %QdObj*  @qd_floordiv(%QdObj*, %QdObj*)
declare %QdObj*  @qd_mod(%QdObj*, %QdObj*)
declare %QdObj*  @qd_pow(%QdObj*, %QdObj*)
declare %QdObj*  @qd_neg(%QdObj*)
declare %QdObj*  @qd_not(%QdObj*)
declare %QdObj*  @qd_cmp_eq(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_ne(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_lt(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_le(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_gt(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_ge(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_is(%QdObj*, %QdObj*)
declare %QdObj*  @qd_getattr(%QdObj*, i8*)
declare void      @qd_setattr(%QdObj*, i8*, %QdObj*)
declare %QdObj*  @qd_getitem(%QdObj*, %QdObj*)
declare void      @qd_setitem(%QdObj*, %QdObj*, %QdObj*)
declare void      @qd_list_append(%QdObj*, %QdObj*)
declare %QdIter* @qd_iter_new(%QdObj*)
declare %QdObj*  @qd_iter_next(%QdIter*)
declare i32       @qd_iter_done(%QdIter*)
declare %QdObj*  @qd_call(%QdObj*, %QdObj**, i32)
declare i32       @qd_truthy(%QdObj*)
declare void      @qd_print(%QdObj*)
declare void      @qd_env_init()
declare void      @qd_env_set(i8*, %QdObj*)
declare %QdObj*  @qd_env_get(i8*)
declare void      @exit(i32) noreturn

@.str.0 = private unnamed_addr constant [3 x i8] c"t0\00"
@.str.1 = private unnamed_addr constant [2 x i8] c"x\00"
@.str.2 = private unnamed_addr constant [3 x i8] c"t1\00"
@.str.3 = private unnamed_addr constant [2 x i8] c"y\00"
@.str.4 = private unnamed_addr constant [3 x i8] c"t2\00"
@.str.5 = private unnamed_addr constant [3 x i8] c"t3\00"
@.str.6 = private unnamed_addr constant [3 x i8] c"t4\00"
@.str.7 = private unnamed_addr constant [2 x i8] c"z\00"
@.str.8 = private unnamed_addr constant [6 x i8] c"print\00"
@.str.9 = private unnamed_addr constant [3 x i8] c"t5\00"
@.str.10 = private unnamed_addr constant [3 x i8] c"t6\00"
@.str.11 = private unnamed_addr constant [6 x i8] c"hello\00"
@.str.12 = private unnamed_addr constant [3 x i8] c"t7\00"
@.str.13 = private unnamed_addr constant [4 x i8] c"msg\00"
@.str.14 = private unnamed_addr constant [3 x i8] c"t8\00"
@.str.15 = private unnamed_addr constant [3 x i8] c"t9\00"
@.str.16 = private unnamed_addr constant [4 x i8] c"lst\00"
@.str.17 = private unnamed_addr constant [4 x i8] c"t10\00"
@.str.18 = private unnamed_addr constant [2 x i8] c"i\00"
@.str.19 = private unnamed_addr constant [7 x i8] c"L_loop\00"
@.str.20 = private unnamed_addr constant [4 x i8] c"t11\00"
@.str.21 = private unnamed_addr constant [4 x i8] c"t12\00"
@.str.22 = private unnamed_addr constant [4 x i8] c"t13\00"
@.str.23 = private unnamed_addr constant [6 x i8] c"L_end\00"
@.str.24 = private unnamed_addr constant [4 x i8] c"t14\00"
@.str.25 = private unnamed_addr constant [4 x i8] c"t15\00"
@.str.26 = private unnamed_addr constant [4 x i8] c"t16\00"
@.str.27 = private unnamed_addr constant [4 x i8] c"t17\00"
@.str.28 = private unnamed_addr constant [4 x i8] c"t18\00"
@.str.29 = private unnamed_addr constant [4 x i8] c"t19\00"
@.str.30 = private unnamed_addr constant [4 x i8] c"t20\00"
@.str.31 = private unnamed_addr constant [4 x i8] c"t21\00"
@.str.32 = private unnamed_addr constant [4 x i8] c"t22\00"
@.str.33 = private unnamed_addr constant [4 x i8] c"t23\00"
@.str.34 = private unnamed_addr constant [7 x i8] c"L_else\00"
@.str.35 = private unnamed_addr constant [4 x i8] c"t24\00"
@.str.36 = private unnamed_addr constant [4 x i8] c"big\00"
@.str.37 = private unnamed_addr constant [4 x i8] c"t25\00"
@.str.38 = private unnamed_addr constant [8 x i8] c"L_ifend\00"
@.str.39 = private unnamed_addr constant [4 x i8] c"t26\00"
@.str.40 = private unnamed_addr constant [6 x i8] c"small\00"
@.str.41 = private unnamed_addr constant [4 x i8] c"t27\00"

define i32 @main() {
entry:
  call void @qd_env_init()

  %t0_slot = alloca %QdObj*
  %x_slot = alloca %QdObj*
  %t1_slot = alloca %QdObj*
  %y_slot = alloca %QdObj*
  %t2_slot = alloca %QdObj*
  %t3_slot = alloca %QdObj*
  %t4_slot = alloca %QdObj*
  %z_slot = alloca %QdObj*
  %t5_slot = alloca %QdObj*
  %t6_slot = alloca %QdObj*
  %t7_slot = alloca %QdObj*
  %msg_slot = alloca %QdObj*
  %t8_slot = alloca %QdObj*
  %t9_slot = alloca %QdObj*
  %lst_slot = alloca %QdObj*
  %t10_slot = alloca %QdObj*
  %i_slot = alloca %QdObj*
  %t11_slot = alloca %QdObj*
  %t12_slot = alloca %QdObj*
  %t13_slot = alloca %QdObj*
  %L_end_slot = alloca %QdObj*
  %t14_slot = alloca %QdObj*
  %t15_slot = alloca %QdObj*
  %t16_slot = alloca %QdObj*
  %t17_slot = alloca %QdObj*
  %t18_slot = alloca %QdObj*
  %t19_slot = alloca %QdObj*
  %t20_slot = alloca %QdObj*
  %t21_slot = alloca %QdObj*
  %t22_slot = alloca %QdObj*
  %t23_slot = alloca %QdObj*
  %L_else_slot = alloca %QdObj*
  %t24_slot = alloca %QdObj*
  %t25_slot = alloca %QdObj*
  %t26_slot = alloca %QdObj*
  %t27_slot = alloca %QdObj*

  %_v0 = call %QdObj* @qd_int(i64 10)
  store %QdObj* %_v0, %QdObj** %t0_slot
  %_v1 = load %QdObj*, %QdObj** %t0_slot
  store %QdObj* %_v1, %QdObj** %x_slot
  %_cs2 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.1, i32 0, i32 0
  call void @qd_env_set(i8* %_cs2, %QdObj* %_v1)
  %_v3 = call %QdObj* @qd_int(i64 3)
  store %QdObj* %_v3, %QdObj** %t1_slot
  %_v4 = load %QdObj*, %QdObj** %t1_slot
  store %QdObj* %_v4, %QdObj** %y_slot
  %_cs5 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.3, i32 0, i32 0
  call void @qd_env_set(i8* %_cs5, %QdObj* %_v4)
  %_v6 = load %QdObj*, %QdObj** %x_slot
  store %QdObj* %_v6, %QdObj** %t2_slot
  %_v7 = load %QdObj*, %QdObj** %y_slot
  store %QdObj* %_v7, %QdObj** %t3_slot
  %_v8 = load %QdObj*, %QdObj** %t2_slot
  %_v9 = load %QdObj*, %QdObj** %t3_slot
  %_ar10 = call %QdObj* @qd_add(%QdObj* %_v9, %QdObj* %_v9)
  store %QdObj* %_ar10, %QdObj** %t4_slot
  %_v11 = load %QdObj*, %QdObj** %t4_slot
  store %QdObj* %_v11, %QdObj** %z_slot
  %_cs12 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.7, i32 0, i32 0
  call void @qd_env_set(i8* %_cs12, %QdObj* %_v11)
  %_cs13 = getelementptr inbounds [6 x i8], [6 x i8]* @.str.8, i32 0, i32 0
  %_ln14 = call %QdObj* @qd_env_get(i8* %_cs13)
  store %QdObj* %_ln14, %QdObj** %t5_slot
  %_v15 = load %QdObj*, %QdObj** %z_slot
  store %QdObj* %_v15, %QdObj** %t6_slot
  %_v16 = load %QdObj*, %QdObj** %t6_slot
  %_v17 = load %QdObj*, %QdObj** %t5_slot
  %_argv18 = alloca %QdObj*, i32 1
  %_ap19 = getelementptr %QdObj*, %QdObj** %_argv18, i32 0
  store %QdObj* %_v16, %QdObj** %_ap19
  %_cr20 = call %QdObj* @qd_call(%QdObj* %_v17, %QdObj** %_argv18, i32 1)
  %_gp22 = getelementptr inbounds [6 x i8], [6 x i8]* @.str.11, i32 0, i32 0
  %_v21 = call %QdObj* @qd_string(i8* %_gp22)
  store %QdObj* %_v21, %QdObj** %t7_slot
  %_v23 = load %QdObj*, %QdObj** %t7_slot
  store %QdObj* %_v23, %QdObj** %msg_slot
  %_cs24 = getelementptr inbounds [4 x i8], [4 x i8]* @.str.13, i32 0, i32 0
  call void @qd_env_set(i8* %_cs24, %QdObj* %_v23)
  %_cs25 = getelementptr inbounds [6 x i8], [6 x i8]* @.str.8, i32 0, i32 0
  %_ln26 = call %QdObj* @qd_env_get(i8* %_cs25)
  store %QdObj* %_ln26, %QdObj** %t8_slot
  %_v27 = load %QdObj*, %QdObj** %msg_slot
  store %QdObj* %_v27, %QdObj** %t9_slot
  %_v28 = load %QdObj*, %QdObj** %t9_slot
  %_v29 = load %QdObj*, %QdObj** %t8_slot
  %_argv30 = alloca %QdObj*, i32 1
  %_ap31 = getelementptr %QdObj*, %QdObj** %_argv30, i32 0
  store %QdObj* %_v28, %QdObj** %_ap31
  %_cr32 = call %QdObj* @qd_call(%QdObj* %_v29, %QdObj** %_argv30, i32 1)
  %_bl33 = call %QdObj* @qd_list_new()
  store %QdObj* %_bl33, %QdObj** %lst_slot
  %_v34 = load %QdObj*, %QdObj** %lst_slot
  store %QdObj* %_v34, %QdObj** %lst_slot
  %_cs35 = getelementptr inbounds [4 x i8], [4 x i8]* @.str.16, i32 0, i32 0
  call void @qd_env_set(i8* %_cs35, %QdObj* %_v34)
  %_v36 = call %QdObj* @qd_int(i64 0)
  store %QdObj* %_v36, %QdObj** %t10_slot
  %_v37 = load %QdObj*, %QdObj** %t10_slot
  store %QdObj* %_v37, %QdObj** %i_slot
  %_cs38 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.18, i32 0, i32 0
  call void @qd_env_set(i8* %_cs38, %QdObj* %_v37)
  br label %L_loop

L_loop:
  %_v39 = load %QdObj*, %QdObj** %i_slot
  store %QdObj* %_v39, %QdObj** %t11_slot
  %_v40 = call %QdObj* @qd_int(i64 5)
  store %QdObj* %_v40, %QdObj** %t12_slot
  %_v41 = load %QdObj*, %QdObj** %t11_slot
  %_v42 = load %QdObj*, %QdObj** %t12_slot
  %_cm43 = call %QdObj* @qd_cmp_ge(%QdObj* %_v42, %QdObj* %_v42)
  store %QdObj* %_cm43, %QdObj** %t13_slot
  %_v44 = load %QdObj*, %QdObj** %t13_slot
  %_bt45 = call i32 @qd_truthy(%QdObj* %_v44)
  %_bc46 = icmp ne i32 %_bt45, 0
  br i1 %_bc46, label %L_end, label %_fall47

_fall47:
  %_v48 = load %QdObj*, %QdObj** %lst_slot
  store %QdObj* %_v48, %QdObj** %t14_slot
  %_v49 = load %QdObj*, %QdObj** %i_slot
  store %QdObj* %_v49, %QdObj** %t15_slot
  %_v50 = load %QdObj*, %QdObj** %t14_slot
  %_v51 = load %QdObj*, %QdObj** %t15_slot
  call void @qd_list_append(%QdObj* %_v51, %QdObj* %_v51)
  %_v52 = load %QdObj*, %QdObj** %i_slot
  store %QdObj* %_v52, %QdObj** %t16_slot
  %_v53 = call %QdObj* @qd_int(i64 1)
  store %QdObj* %_v53, %QdObj** %t17_slot
  %_v54 = load %QdObj*, %QdObj** %t16_slot
  %_v55 = load %QdObj*, %QdObj** %t17_slot
  %_ar56 = call %QdObj* @qd_add(%QdObj* %_v55, %QdObj* %_v55)
  store %QdObj* %_ar56, %QdObj** %t18_slot
  %_v57 = load %QdObj*, %QdObj** %t18_slot
  store %QdObj* %_v57, %QdObj** %i_slot
  %_cs58 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.18, i32 0, i32 0
  call void @qd_env_set(i8* %_cs58, %QdObj* %_v57)
  br label %L_loop

L_end:
  %_cs59 = getelementptr inbounds [6 x i8], [6 x i8]* @.str.8, i32 0, i32 0
  %_ln60 = call %QdObj* @qd_env_get(i8* %_cs59)
  store %QdObj* %_ln60, %QdObj** %t19_slot
  %_v61 = load %QdObj*, %QdObj** %lst_slot
  store %QdObj* %_v61, %QdObj** %t20_slot
  %_v62 = load %QdObj*, %QdObj** %t20_slot
  %_v63 = load %QdObj*, %QdObj** %t19_slot
  %_argv64 = alloca %QdObj*, i32 1
  %_ap65 = getelementptr %QdObj*, %QdObj** %_argv64, i32 0
  store %QdObj* %_v62, %QdObj** %_ap65
  %_cr66 = call %QdObj* @qd_call(%QdObj* %_v63, %QdObj** %_argv64, i32 1)
  %_v67 = load %QdObj*, %QdObj** %x_slot
  store %QdObj* %_v67, %QdObj** %t21_slot
  %_v68 = call %QdObj* @qd_int(i64 5)
  store %QdObj* %_v68, %QdObj** %t22_slot
  %_v69 = load %QdObj*, %QdObj** %t21_slot
  %_v70 = load %QdObj*, %QdObj** %t22_slot
  %_cm71 = call %QdObj* @qd_cmp_gt(%QdObj* %_v70, %QdObj* %_v70)
  store %QdObj* %_cm71, %QdObj** %t23_slot
  %_v72 = load %QdObj*, %QdObj** %t23_slot
  %_bt73 = call i32 @qd_truthy(%QdObj* %_v72)
  %_bc74 = icmp ne i32 %_bt73, 0
  br i1 %_bc74, label %_fall75, label %L_else

_fall75:
  %_cs76 = getelementptr inbounds [6 x i8], [6 x i8]* @.str.8, i32 0, i32 0
  %_ln77 = call %QdObj* @qd_env_get(i8* %_cs76)
  store %QdObj* %_ln77, %QdObj** %t24_slot
  %_gp79 = getelementptr inbounds [4 x i8], [4 x i8]* @.str.36, i32 0, i32 0
  %_v78 = call %QdObj* @qd_string(i8* %_gp79)
  store %QdObj* %_v78, %QdObj** %t25_slot
  %_v80 = load %QdObj*, %QdObj** %t25_slot
  %_v81 = load %QdObj*, %QdObj** %t24_slot
  %_argv82 = alloca %QdObj*, i32 1
  %_ap83 = getelementptr %QdObj*, %QdObj** %_argv82, i32 0
  store %QdObj* %_v80, %QdObj** %_ap83
  %_cr84 = call %QdObj* @qd_call(%QdObj* %_v81, %QdObj** %_argv82, i32 1)
  br label %L_ifend

L_else:
  %_cs85 = getelementptr inbounds [6 x i8], [6 x i8]* @.str.8, i32 0, i32 0
  %_ln86 = call %QdObj* @qd_env_get(i8* %_cs85)
  store %QdObj* %_ln86, %QdObj** %t26_slot
  %_gp88 = getelementptr inbounds [6 x i8], [6 x i8]* @.str.40, i32 0, i32 0
  %_v87 = call %QdObj* @qd_string(i8* %_gp88)
  store %QdObj* %_v87, %QdObj** %t27_slot
  %_v89 = load %QdObj*, %QdObj** %t27_slot
  %_v90 = load %QdObj*, %QdObj** %t26_slot
  %_argv91 = alloca %QdObj*, i32 1
  %_ap92 = getelementptr %QdObj*, %QdObj** %_argv91, i32 0
  store %QdObj* %_v89, %QdObj** %_ap92
  %_cr93 = call %QdObj* @qd_call(%QdObj* %_v90, %QdObj** %_argv91, i32 1)
  br label %L_ifend

L_ifend:

  ret i32 0
}
